// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Body is the request body. Exactly one of Raw or FilePath is set, or
 * neither for a body-less request.
 */
export interface Body {
    /**
     * Raw is the body text verbatim, minus leading and trailing blank lines
     * and minus the final line terminator. Internal blank lines, trailing
     * spaces and indentation are preserved.
     */
    "raw"?: string;

    /**
     * FilePath is set for a "< ./path" body. The path is recorded relative
     * to the .http file and is not read by the parser.
     */
    "filePath"?: string;

    /**
     * SubstituteVariables is true for the "<@ ./path" form, which asks for
     * {{variables}} inside the referenced file to be resolved.
     */
    "substituteVariables"?: boolean;

    /**
     * Encoding is the optional charset of the "<@charset ./path" form.
     */
    "encoding"?: string;

    /**
     * Line is the first line of the body, 0 if there is no body.
     */
    "line"?: number;
}

/**
 * Comment is a "#" or "//" comment line outside a body that is not a
 * directive.
 */
export interface Comment {
    /**
     * Style is "#" or "//".
     */
    "style": string;

    /**
     * Text is everything after the comment marker, verbatim.
     */
    "text": string;
    "line"?: number;
}

/**
 * Directive is a comment of the form "# @name value" or "// @name value".
 * Value is empty for flag directives such as "# @no-redirect".
 */
export interface Directive {
    "style": string;
    "name": string;
    "value"?: string;
    "line"?: number;
}

/**
 * File is one parsed .http file. A file holds zero or more entries separated
 * by "###" lines. By Otis convention a request file holds exactly one entry
 * with a request line; _folder.http files hold one entry without one.
 */
export interface File {
    "requests": (Request | null)[] | null;
}

/**
 * Header is one request header. Name keeps its original casing and headers
 * keep their original order.
 */
export interface Header {
    "name": string;
    "value": string;
    "line"?: number;
}

/**
 * Redirect is a ">> ./path" or ">>! ./path" response-to-file instruction.
 */
export interface Redirect {
    "path": string;

    /**
     * Force is true for the ">>!" form, which overwrites an existing file.
     */
    "force"?: boolean;
    "line"?: number;
}

/**
 * Request is one "###"-delimited entry of a file.
 * 
 * An entry without a request line (Method == "") is legal: it carries only
 * comments, directives, variables and headers. That is how _folder.http
 * expresses settings that cascade to the requests below it.
 */
export interface Request {
    /**
     * Title is the text following the "###" separator, if any.
     */
    "title"?: string;

    /**
     * SeparatorLine is the 1-based line of the "###" separator, 0 if the
     * entry is the first in the file and has no separator.
     */
    "separatorLine"?: number;

    /**
     * Preamble items. Their relative order in the source is recoverable
     * from Line; the serializer preserves it.
     */
    "comments"?: Comment[] | null;
    "variables"?: Variable[] | null;
    "directives"?: Directive[] | null;
    "preScripts"?: Script[] | null;

    /**
     * Request line. Method is empty when the entry has no request line.
     */
    "method"?: string;
    "url"?: string;
    "version"?: string;
    "line"?: number;
    "headers"?: Header[] | null;
    "body": Body;
    "postScripts"?: Script[] | null;
    "redirect"?: Redirect | null;
}

/**
 * Script is a "< {% ... %}" pre-request or "> {% ... %}" post-response
 * block, or the "> ./handler.js" external form. Text is the content between
 * "{%" and "%}" verbatim, including surrounding newlines.
 */
export interface Script {
    "text"?: string;

    /**
     * FilePath is set for the external "> ./handler.js" form.
     */
    "filePath"?: string;
    "line"?: number;
}

/**
 * Variable is a file-level "@name = value" declaration.
 */
export interface Variable {
    "name": string;
    "value": string;
    "line"?: number;
}
