// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService is the root service of Otis. It carries app-level metadata and
 * a health check used to prove the binding channel works.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * Ping echoes msg back with a timestamp. It returns an error for an empty
 * message so the error path of the binding channel is exercised too.
 */
export function Ping(msg: string): $CancellablePromise<string> {
    return $Call.ByID(3586373625, msg);
}

/**
 * Version returns the build-time version string.
 */
export function Version(): $CancellablePromise<string> {
    return $Call.ByID(1375003879);
}
