// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CollectionService owns the one piece of app-level state everything else
 * hangs off: which collection is open, its tree, and the watcher keeping that
 * tree true.
 * 
 * Changing the collection emits events.CollectionOpened; a change on disk
 * emits events.CollectionChanged with the new tree; a commit, stage or branch
 * switch emits events.GitChanged. No part of the frontend polls.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as collection$0 from "../collection/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as watch$0 from "../watch/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AbsolutePath resolves a collection-relative node path to an absolute one.
 */
export function AbsolutePath(nodePath: string): $CancellablePromise<string> {
    return $Call.ByID(4097260546, nodePath);
}

/**
 * Close forgets the current collection and emits events.CollectionOpened with
 * an empty path, which returns the window to the empty state.
 */
export function Close(): $CancellablePromise<void> {
    return $Call.ByID(394227296);
}

/**
 * CopyPath puts a node's absolute path on the clipboard and returns what it
 * copied.
 * 
 * The absolute path, not the collection-relative one: the relative path is
 * already on screen next to the row, and what you want on the clipboard is
 * the thing you can paste into a terminal or another editor. Copying goes
 * through Go rather than navigator.clipboard because the window is served
 * from a custom scheme, where the browser clipboard API is not reliably
 * available.
 */
export function CopyPath(nodePath: string): $CancellablePromise<string> {
    return $Call.ByID(3234360442, nodePath);
}

/**
 * Current returns the open collection, or the zero value if there is none.
 */
export function Current(): $CancellablePromise<$models.CollectionInfo> {
    return $Call.ByID(68784281);
}

/**
 * Guard is the write guard every writer to a collection must hold, so Otis'
 * own writes are not mistaken for someone else's.
 */
export function Guard(): $CancellablePromise<watch$0.Guard | null> {
    return $Call.ByID(2575404401);
}

/**
 * Loaded returns the current collection as last walked, walking it now if
 * nothing is cached. Callers get the tree the window is showing, so a request
 * resolves against the same files the sidebar drew.
 */
export function Loaded(): $CancellablePromise<collection$0.Collection | null> {
    return $Call.ByID(1400029889);
}

/**
 * NotifyDiskChange runs the OnDiskChange functions.
 * 
 * It is for a writer that changed a file the *tree* does not cover, and so
 * cannot rely on Refresh to announce it: a script writing an environment file
 * through vars.env.set is the case. The guard means the watcher will not
 * report the write, so the writer has to.
 */
export function NotifyDiskChange(): $CancellablePromise<void> {
    return $Call.ByID(1505448452);
}

/**
 * OnClose registers a function to run when the current collection is closed or
 * replaced. It is how the state that belongs to a collection rather than to
 * the process — the cookie jar, the AWS credential cache, the session
 * variables — gets dropped without this service knowing what any of it is.
 */
export function OnClose(fn: any): $CancellablePromise<void> {
    return $Call.ByID(31780067, fn);
}

/**
 * OnDiskChange registers a function to run when something in the collection
 * directory changed underneath Otis — the watcher's report, not a write Otis
 * made itself.
 * 
 * It is how a service that owns part of the collection the *tree* does not
 * cover gets told to re-read: env/ is not part of the tree (docs/FORMAT.md
 * §2.1), so events.CollectionChanged says nothing about an environment file
 * somebody edited in another editor. A write Otis makes announces itself
 * instead (see Refresh), so these do not fire for it.
 */
export function OnDiskChange(fn: any): $CancellablePromise<void> {
    return $Call.ByID(4032293140, fn);
}

/**
 * Open makes dir the current collection: it walks the tree, reads the
 * repository, starts watching for changes, records dir in the recents list and
 * as the collection to reopen next launch, then emits events.CollectionOpened.
 */
export function Open(dir: string): $CancellablePromise<$models.Opened> {
    return $Call.ByID(591253948, dir);
}

/**
 * OpenPath opens whatever the OS handed Otis and tells the window to show it.
 * 
 * It is the one entry point for a path that came from outside the window: a
 * .http file double-clicked in Finder or Explorer, a path on the command line
 * (`otis .`), a second launch forwarding its arguments, and a file dropped on
 * the window. All four mean the same thing — "show me this" — and all four
 * have to agree about which collection that is, which is why they share this
 * method rather than each calling Open with a directory they worked out
 * themselves.
 * 
 * A directory opens as a collection, as the dialog and a dropped folder do. A
 * file opens the collection *around* it, found with collection.FindRoot — the
 * same walk `otis run` uses (docs/FORMAT.md §8), so a request resolves against
 * the same root from the desktop as from the terminal.
 * 
 * The node is then addressed inside that collection. A `_folder.http` resolves
 * to its folder rather than to itself, because it is settings and not a tree
 * row (docs/FORMAT.md §2.1); every other .http file is a request.
 * 
 * The window may not exist yet — the file association starts the process — so
 * the target is held until a window's runtime is ready and emitted then. The
 * collection is opened either way: events.CollectionOpened is what draws the
 * tree, and it goes through the same wait.
 */
export function OpenPath(path: string): $CancellablePromise<void> {
    return $Call.ByID(3869136571, path);
}

/**
 * Refresh re-walks the collection, caches the walk and tells the window.
 * 
 * It is how a write Otis makes itself becomes visible. The watcher cannot do
 * it: every writer holds the write guard so that its own save is *not*
 * reported as an external change, which means the save has to announce itself.
 */
export function Refresh(): $CancellablePromise<void> {
    return $Call.ByID(651601255);
}

/**
 * Reveal shows a node in the OS file manager. nodePath is collection-relative.
 */
export function Reveal(nodePath: string): $CancellablePromise<void> {
    return $Call.ByID(217242705, nodePath);
}

/**
 * TakePendingOpen returns the node an OS-level open asked for, and forgets it.
 * 
 * A pull rather than a push, because the push cannot be timed. Wails raises
 * WindowRuntimeReady when the webview's JS runtime loads, which is before the
 * React tree has mounted and therefore before anything is listening — so a
 * target emitted then is simply lost, which is exactly what happened the first
 * time a .http file was double-clicked: the collection opened and the window
 * sat on the empty centre pane. The window asking when it is ready has no such
 * window of failure.
 * 
 * It clears as it reads so a remount does not re-navigate somewhere the user
 * has since navigated away from, and so the events.OpenNode nudge and the
 * on-mount call cannot both act on one open.
 * 
 * Kind is empty when there is nothing pending, which is the normal answer.
 */
export function TakePendingOpen(): $CancellablePromise<$models.OpenTarget> {
    return $Call.ByID(2105506542);
}

/**
 * Tree re-walks the open collection and returns it. The window does not need
 * to call this in the normal course of things — changes arrive as
 * events.CollectionChanged — but it is how a view recovers after an error.
 */
export function Tree(): $CancellablePromise<$models.Tree> {
    return $Call.ByID(4254259948);
}
