// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CollectionService owns the one piece of app-level state everything else
 * hangs off: which collection is open. Changing it emits
 * events.CollectionOpened, so no part of the frontend has to poll or keep its
 * own copy.
 * 
 * Increment 9 grows this service into the tree loader and file watcher; for
 * now Open only validates the directory and records it.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Close forgets the current collection and emits events.CollectionOpened with
 * an empty path, which returns the window to the empty state.
 */
export function Close(): $CancellablePromise<void> {
    return $Call.ByID(394227296);
}

/**
 * Current returns the open collection, or the zero value if there is none.
 */
export function Current(): $CancellablePromise<$models.CollectionInfo> {
    return $Call.ByID(68784281);
}

/**
 * Open makes dir the current collection. It records dir in the recents list
 * and as the collection to reopen on the next launch, then emits
 * events.CollectionOpened.
 */
export function Open(dir: string): $CancellablePromise<$models.CollectionInfo> {
    return $Call.ByID(591253948, dir);
}
