// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CollectionService owns the one piece of app-level state everything else
 * hangs off: which collection is open, its tree, and the watcher keeping that
 * tree true.
 * 
 * Changing the collection emits events.CollectionOpened; a change on disk
 * emits events.CollectionChanged with the new tree; a commit, stage or branch
 * switch emits events.GitChanged. No part of the frontend polls.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as collection$0 from "../collection/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as watch$0 from "../watch/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AbsolutePath resolves a collection-relative node path to an absolute one.
 */
export function AbsolutePath(nodePath: string): $CancellablePromise<string> {
    return $Call.ByID(4097260546, nodePath);
}

/**
 * Close forgets the current collection and emits events.CollectionOpened with
 * an empty path, which returns the window to the empty state.
 */
export function Close(): $CancellablePromise<void> {
    return $Call.ByID(394227296);
}

/**
 * CopyPath puts a node's absolute path on the clipboard and returns what it
 * copied.
 * 
 * The absolute path, not the collection-relative one: the relative path is
 * already on screen next to the row, and what you want on the clipboard is
 * the thing you can paste into a terminal or another editor. Copying goes
 * through Go rather than navigator.clipboard because the window is served
 * from a custom scheme, where the browser clipboard API is not reliably
 * available.
 */
export function CopyPath(nodePath: string): $CancellablePromise<string> {
    return $Call.ByID(3234360442, nodePath);
}

/**
 * Current returns the open collection, or the zero value if there is none.
 */
export function Current(): $CancellablePromise<$models.CollectionInfo> {
    return $Call.ByID(68784281);
}

/**
 * Guard is the write guard every writer to a collection must hold, so Otis'
 * own writes are not mistaken for someone else's.
 */
export function Guard(): $CancellablePromise<watch$0.Guard | null> {
    return $Call.ByID(2575404401);
}

/**
 * Loaded returns the current collection as last walked, walking it now if
 * nothing is cached. Callers get the tree the window is showing, so a request
 * resolves against the same files the sidebar drew.
 */
export function Loaded(): $CancellablePromise<collection$0.Collection | null> {
    return $Call.ByID(1400029889);
}

/**
 * OnClose registers a function to run when the current collection is closed or
 * replaced. It is how the state that belongs to a collection rather than to
 * the process — the cookie jar, the AWS credential cache, the session
 * variables — gets dropped without this service knowing what any of it is.
 */
export function OnClose(fn: any): $CancellablePromise<void> {
    return $Call.ByID(31780067, fn);
}

/**
 * OnDiskChange registers a function to run when something in the collection
 * directory changed underneath Otis — the watcher's report, not a write Otis
 * made itself.
 * 
 * It is how a service that owns part of the collection the *tree* does not
 * cover gets told to re-read: env/ is not part of the tree (docs/FORMAT.md
 * §2.1), so events.CollectionChanged says nothing about an environment file
 * somebody edited in another editor. A write Otis makes announces itself
 * instead (see Refresh), so these do not fire for it.
 */
export function OnDiskChange(fn: any): $CancellablePromise<void> {
    return $Call.ByID(4032293140, fn);
}

/**
 * Open makes dir the current collection: it walks the tree, reads the
 * repository, starts watching for changes, records dir in the recents list and
 * as the collection to reopen next launch, then emits events.CollectionOpened.
 */
export function Open(dir: string): $CancellablePromise<$models.Opened> {
    return $Call.ByID(591253948, dir);
}

/**
 * Refresh re-walks the collection, caches the walk and tells the window.
 * 
 * It is how a write Otis makes itself becomes visible. The watcher cannot do
 * it: every writer holds the write guard so that its own save is *not*
 * reported as an external change, which means the save has to announce itself.
 */
export function Refresh(): $CancellablePromise<void> {
    return $Call.ByID(651601255);
}

/**
 * Reveal shows a node in the OS file manager. nodePath is collection-relative.
 */
export function Reveal(nodePath: string): $CancellablePromise<void> {
    return $Call.ByID(217242705, nodePath);
}

/**
 * Tree re-walks the open collection and returns it. The window does not need
 * to call this in the normal course of things — changes arrive as
 * events.CollectionChanged — but it is how a view recovers after an error.
 */
export function Tree(): $CancellablePromise<$models.Tree> {
    return $Call.ByID(4254259948);
}
