// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DialogService exposes the native file dialogs. The frontend never touches
 * the filesystem itself; picking a directory is a Go call that returns a path.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * OpenCollectionParent shows the directory picker for where a *new* collection
 * should be created or cloned — the folder that will contain it, not the
 * collection itself, which does not exist yet.
 * 
 * One picker for both of screen 2b's remaining cards. They ask the same
 * question and the name is typed in the dialog either way, so a second
 * method here would differ only in its title.
 */
export function OpenCollectionParent(): $CancellablePromise<string> {
    return $Call.ByID(467015268);
}

/**
 * OpenDirectory shows the native directory picker and returns the chosen
 * absolute path. Cancelling returns "" with no error: the user declining is
 * not a failure, and every caller has to handle the empty string anyway.
 */
export function OpenDirectory(): $CancellablePromise<string> {
    return $Call.ByID(2241080147);
}

/**
 * OpenImportDestination shows the directory picker for where an import
 * should land.
 */
export function OpenImportDestination(): $CancellablePromise<string> {
    return $Call.ByID(1800079047);
}

/**
 * OpenPostmanExport shows the native file picker for a Postman export.
 * 
 * Cancelling returns "" with no error, the same as OpenDirectory: a person
 * declining is not a failure.
 */
export function OpenPostmanExport(): $CancellablePromise<string> {
    return $Call.ByID(85323164);
}
