// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DialogService exposes the native file dialogs. The frontend never touches
 * the filesystem itself; picking a directory is a Go call that returns a path.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * OpenDirectory shows the native directory picker and returns the chosen
 * absolute path. Cancelling returns "" with no error: the user declining is
 * not a failure, and every caller has to handle the empty string anyway.
 */
export function OpenDirectory(): $CancellablePromise<string> {
    return $Call.ByID(2241080147);
}
