// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DiffService is the git diff view (screen 1b).
 * 
 * It is the only service that writes to a repository, and only the writes a
 * review needs: the index, and a commit on the current branch. GitService
 * stays read-only and answers "what does git think" for the tree dots and the
 * status bar.
 * 
 * Every mutating method emits events.GitChanged, so the tree, the status bar
 * and this view are never out of step with each other — and Discard, which
 * writes a file in the collection, also refreshes the collection so the
 * window sees the file it now is.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as diff$0 from "../diff/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Commit records everything staged with message and returns the new commit
 * along with the view as it now is.
 * 
 * Everything staged, which is the repository's index and not only the
 * collection's part of it: a commit made here includes anything staged
 * outside the collection too. That is what git does, and the view says so
 * beside the button rather than pretending otherwise.
 */
export function Commit(message: string): $CancellablePromise<$models.CommitResult> {
    return $Call.ByID(423106090, message);
}

/**
 * DiscardFile throws away a whole file's uncommitted changes: the working
 * tree returns to HEAD, and an untracked file is deleted.
 * 
 * **Destructive.** confirm must be true or the call is refused with
 * diff.ErrNoConfirm. The distinct name and the flag are deliberate: this is
 * the only operation in Otis that destroys work git cannot get back, and a
 * second caller — the CLI, the MCP server — must not be able to reach it by
 * picking the wrong method off this service. The dialog in front of it is a
 * courtesy on top, not the safety.
 */
export function DiscardFile(nodePath: string, confirm: boolean): $CancellablePromise<diff$0.Overview> {
    return $Call.ByID(3698058705, nodePath, confirm);
}

/**
 * DiscardHunks throws away the named hunks in the working tree, leaving the
 * rest.
 * 
 * **Destructive**, on the same terms as DiscardFile: confirm must be true.
 */
export function DiscardHunks(nodePath: string, hunks: number[] | null, confirm: boolean): $CancellablePromise<diff$0.Overview> {
    return $Call.ByID(3934352864, nodePath, hunks, confirm);
}

/**
 * File returns one file's diff, working tree against HEAD. nodePath is
 * collection-relative.
 */
export function File(nodePath: string): $CancellablePromise<diff$0.FileDiff> {
    return $Call.ByID(3996826317, nodePath);
}

/**
 * Overview lists every change under the collection root.
 * 
 * A collection outside a repository yields Overview{Repository: false} and no
 * error: that is a normal state and one of the view's empty cases, not a
 * failure.
 */
export function Overview(): $CancellablePromise<diff$0.Overview> {
    return $Call.ByID(3963768236);
}

/**
 * Stage stages a whole file.
 */
export function Stage(nodePath: string): $CancellablePromise<diff$0.Overview> {
    return $Call.ByID(95912063, nodePath);
}

/**
 * StageAll stages every change under the collection root.
 */
export function StageAll(): $CancellablePromise<diff$0.Overview> {
    return $Call.ByID(3422931562);
}

/**
 * StageHunks stages the named hunks of a file. The numbers index the FileDiff
 * the window is showing; the diff is recomputed here and the numbers checked
 * against it, so a stale view cannot stage something else.
 */
export function StageHunks(nodePath: string, hunks: number[] | null): $CancellablePromise<diff$0.Overview> {
    return $Call.ByID(775638144, nodePath, hunks);
}

/**
 * Unstage returns a whole file's index entry to HEAD, leaving the working
 * tree alone.
 */
export function Unstage(nodePath: string): $CancellablePromise<diff$0.Overview> {
    return $Call.ByID(1824818754, nodePath);
}

/**
 * UnstageHunks unstages the named hunks of a file.
 */
export function UnstageHunks(nodePath: string, hunks: number[] | null): $CancellablePromise<diff$0.Overview> {
    return $Call.ByID(3838126995, nodePath, hunks);
}
