// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * EnvironmentService is the environment editor's service (screen 1c): it
 * lists, reads and writes env/*.json, and it is the only thing that puts a
 * secret into the machine's keychain or takes one out.
 * 
 * # The one rule
 * 
 * A resolved secret value never crosses this boundary. Every method here
 * either takes a value the user just typed (window → Go, which is how a value
 * gets in) or reports *about* a secret without its value (Go → window). There
 * is deliberately no method that returns one. The design's Reveal control is
 * served by CopySecretValue, which puts the value on the system clipboard from
 * Go: the user gets at their own credential, and the webview never holds it.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Activate makes name the active environment, or deactivates every one when
 * name is "". Only the name is persisted (settings.ActiveEnv).
 */
export function Activate(name: string): $CancellablePromise<$models.Environments> {
    return $Call.ByID(3399487746, name);
}

/**
 * CopySecretValue puts a secret's value on the system clipboard and returns
 * nothing.
 * 
 * This is the design's Reveal control (screen 1c), resolved the only way the
 * secrets rule allows. Rendering the value would mean handing it to the
 * webview, where it would sit in a React tree, a DOM node and any devtools
 * session — so Otis does not. The clipboard write happens in Go: the user gets
 * their own credential where they can paste it, and the value never crosses
 * the binding. Nothing is returned but an error, and the error names the key.
 */
export function CopySecretValue(envName: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(2784257087, envName, name);
}

/**
 * Create writes an empty env/<name>.json and returns it.
 */
export function Create(name: string): $CancellablePromise<$models.EnvironmentDocument> {
    return $Call.ByID(2647098239, name);
}

/**
 * Delete removes env/<name>.json.
 * 
 * The values its secret references pointed at are left in the keychain: they
 * belong to the machine, not to the file, and a teammate's branch may still
 * reference them. RemoveVariable is the operation that forgets a value.
 */
export function Delete(name: string): $CancellablePromise<$models.Environments> {
    return $Call.ByID(1054078692, name);
}

/**
 * ForgetSecret removes a secret's value from the keychain and leaves the
 * reference in the file. It is the design's "Remove from keychain": the
 * committed reference is the team's, the value is this machine's, and this
 * gives up only the second.
 */
export function ForgetSecret(envName: string, name: string): $CancellablePromise<$models.EnvironmentDocument> {
    return $Call.ByID(3458071334, envName, name);
}

/**
 * List returns every environment in the collection, with the active one
 * marked. No collection open, or no env/ directory, is an empty list rather
 * than an error: a collection need not have environments at all.
 */
export function List(): $CancellablePromise<$models.Environments> {
    return $Call.ByID(4124109471);
}

/**
 * Load reads one environment for the editor.
 */
export function Load(name: string): $CancellablePromise<$models.EnvironmentDocument> {
    return $Call.ByID(2472274255, name);
}

/**
 * MakeSecret turns a variable into a {"$secret": "keychain"} reference and
 * puts value in the keychain. It is also how a brand-new secret is added.
 * 
 * The keychain write comes first: a file that references a value which is not
 * there is a request that fails at send time, while a value in the keychain
 * that nothing references yet is inert.
 */
export function MakeSecret(envName: string, name: string, value: string): $CancellablePromise<$models.EnvironmentDocument> {
    return $Call.ByID(773253873, envName, name, value);
}

/**
 * RemoveVariable removes a variable from the file. A secret's stored value is
 * removed from the keychain with it: a value nobody can see and nothing
 * references is the worst of the three outcomes, so the reference and the
 * value go together.
 */
export function RemoveVariable(envName: string, name: string): $CancellablePromise<$models.EnvironmentDocument> {
    return $Call.ByID(608650151, envName, name);
}

/**
 * RenameVariable renames a variable in place, keeping its position in the
 * file. A secret's stored value moves with it, so renaming does not silently
 * orphan the value.
 */
export function RenameVariable(envName: string, $from: string, to: string): $CancellablePromise<$models.EnvironmentDocument> {
    return $Call.ByID(2665433485, envName, $from, to);
}

/**
 * SetConfirmBeforeSend writes the environment's "$otis" confirmBeforeSend
 * setting. It is committed on purpose: the whole team should get the same
 * warning on the same environment, and a change to it should show up in
 * review.
 */
export function SetConfirmBeforeSend(envName: string, on: boolean): $CancellablePromise<$models.EnvironmentDocument> {
    return $Call.ByID(24482542, envName, on);
}

/**
 * SetDescription writes the environment's "$otis" description.
 */
export function SetDescription(envName: string, description: string): $CancellablePromise<$models.EnvironmentDocument> {
    return $Call.ByID(3140669473, envName, description);
}

/**
 * SetSecretValue replaces the stored value of an existing secret reference.
 * It is the design's "Replace value".
 */
export function SetSecretValue(envName: string, name: string, value: string): $CancellablePromise<$models.EnvironmentDocument> {
    return $Call.ByID(2038997574, envName, name, value);
}

/**
 * SetVariable writes a plain variable, creating it if it is new. A row that
 * was a secret becomes plain and its keychain value is forgotten — the file
 * would otherwise say the value is committed while the real one sat in the
 * keychain, unused and unreachable.
 */
export function SetVariable(envName: string, name: string, value: string): $CancellablePromise<$models.EnvironmentDocument> {
    return $Call.ByID(3753008205, envName, name, value);
}
