// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FolderService is the folder view's service (screen 3a): it reads a folder's
 * shared settings with their provenance, the documentation beside them, the
 * scripts that run around every request below, and which descendants opt out
 * of each setting. It is the only thing that writes a `_folder.http`.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as httpfile$0 from "../httpfile/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClearSession forgets the variables a run set for this folder.
 */
export function ClearSession(nodePath: string): $CancellablePromise<$models.FolderDocument> {
    return $Call.ByID(1881364631, nodePath);
}

/**
 * Create makes a new folder inside parentPath and returns its node path.
 * 
 * It writes a `_folder.http` inside it, and that is not optional: **git does
 * not track an empty directory**, so a folder created without a file in it
 * would vanish the moment anyone cloned or checked out the branch — the
 * collection would differ between two people for no visible reason. The
 * Postman importer already does this for the same reason (docs/FORMAT.md §7,
 * "An otherwise empty folder gets a _folder.http with a comment so the
 * directory exists").
 * 
 * The file it writes is a comment and nothing else: no auth, no headers, no
 * variables. A new folder should inherit everything from above and declare
 * nothing, so the comment explains what the file is for and the folder view is
 * where you would add anything (DESIGN-NOTES §9.20).
 * 
 * Like RequestService.Create, it does not touch `.order`: an unlisted
 * directory sorts alphabetically after the listed entries (§2.2).
 */
export function Create(parentPath: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(1285433308, parentPath, name);
}

/**
 * Delete removes the folder at nodePath and everything in it.
 * 
 * The collection root is refused: deleting it would delete the collection out
 * from under the window, and a directory somebody chose in a file dialog is
 * not Otis' to remove.
 */
export function Delete(nodePath: string): $CancellablePromise<void> {
    return $Call.ByID(513135715, nodePath);
}

/**
 * Duplicate copies the folder at nodePath, with everything inside it, into
 * the same parent and returns the copy's node path.
 * 
 * Everything inside it includes each subfolder's `.order`: the copy holds the
 * same entries, so it holds the same arrangement of them. The *parent's*
 * `.order` is untouched, like every other creation — the new folder is
 * unlisted and sorts alphabetically after the listed ones (§2.2).
 */
export function Duplicate(nodePath: string): $CancellablePromise<string> {
    return $Call.ByID(2287315849, nodePath);
}

/**
 * Load reads one folder. nodePath is collection-relative; "" is the root.
 * envName is the active environment, used only to describe which values a
 * {{reference}} would resolve to — never to fetch a secret.
 */
export function Load(nodePath: string, envName: string): $CancellablePromise<$models.FolderDocument> {
    return $Call.ByID(823348532, nodePath, envName);
}

/**
 * Rename renames the folder at nodePath and returns its new node path.
 * 
 * A folder has no `# @name`: its name *is* the directory's name
 * (docs/FORMAT.md §2.1), so this renames the directory and nothing else. The
 * typed name is slugged the same way Create slugs it, so a folder named from
 * the dialog and a folder renamed from it land on the same spelling.
 * 
 * The parent's `.order` keeps the folder's position when it lists it, and a
 * parent with no `.order` does not acquire one.
 */
export function Rename(nodePath: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(3194652986, nodePath, name);
}

/**
 * Save writes a folder's _folder.http and returns the folder as it now is.
 * 
 * The frontend edits the parsed model and hands it back, exactly as the
 * request editor does: Go's serializer stays the only writer of a .http file,
 * so there is one answer to what canonical form is (docs/FORMAT.md §1.13).
 * A folder with no settings file yet gets one.
 */
export function Save(nodePath: string, envName: string, file: httpfile$0.File): $CancellablePromise<$models.FolderDocument> {
    return $Call.ByID(1026360661, nodePath, envName, file);
}

/**
 * SaveReadme writes a folder's README.md.
 */
export function SaveReadme(nodePath: string, envName: string, text: string): $CancellablePromise<$models.FolderDocument> {
    return $Call.ByID(1775924087, nodePath, envName, text);
}
