// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GitService reports the state of the repository the open collection lives in.
 * It is read-only: Otis shows what git thinks and leaves committing to git.
 * 
 * The state also travels with the tree, because a file's status changes at the
 * same moment the file does. This service is for the window asking on its own
 * — after an error, or when it wants the counts without a re-walk.
 * 
 * The collection root lives in CollectionService, so this service borrows it
 * rather than keeping a second copy that could disagree.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as git$0 from "../git/models.js";

/**
 * State reads the repository around the open collection. A collection that is
 * not in a repository yields State{Repository: false} and no error.
 */
export function State(): $CancellablePromise<git$0.State> {
    return $Call.ByID(3153351787);
}
