// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ImportService turns a Postman export into an Otis collection.
 * 
 * The conversion itself is `internal/importer/postman`, which the CLI already
 * uses; this is the window's half of it. What the window adds is the thing a
 * flag cannot: it *plans* first and shows what would be written, including
 * what the importer had to skip, and only writes when a person says so
 * (DESIGN-NOTES §8.2 — every write to disk is announced before it happens).
 * The importer separates Plan from Write precisely so a caller can do that.
 * 
 * An import lands in one of two places, and which one is decided by whether a
 * collection is open:
 * 
 *   - **Nothing open** — a new folder beside the export, named for the
 *     collection. That is how you *get* a collection, which is what the start
 *     screen's card is for.
 *   - **A collection open** — a folder inside it, so a Postman export can be
 *     pulled into a collection you already have. It goes in as a new
 *     subfolder and touches nothing else: `.order` is written into the new
 *     directory (fresh, so there is nothing to preserve — docs/FORMAT.md
 *     §2.2) and the parent's is left alone, so the new folder sorts
 *     alphabetically like anything else added.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Choose opens the file picker and plans what the chosen export would become.
 * 
 * Nothing is written. Cancelling returns a zero plan with no error.
 */
export function Choose(): $CancellablePromise<$models.ImportPlan> {
    return $Call.ByID(888689596);
}

/**
 * ChooseDestination opens the directory picker for a held plan.
 */
export function ChooseDestination(id: string): $CancellablePromise<$models.ImportPlan> {
    return $Call.ByID(1148953260, id);
}

/**
 * Commit writes a held plan and opens or refreshes the collection.
 */
export function Commit(id: string): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(571095616, id);
}

/**
 * Discard drops a plan the person abandoned, so a cancelled import does not
 * keep a whole converted collection in memory.
 */
export function Discard(id: string): $CancellablePromise<void> {
    return $Call.ByID(1562629133, id);
}

/**
 * PlanFile plans an export at a known path, without writing.
 */
export function PlanFile(path: string): $CancellablePromise<$models.ImportPlan> {
    return $Call.ByID(3608045664, path);
}

/**
 * Retarget points a held plan at a directory the person chose.
 */
export function Retarget(id: string, dir: string): $CancellablePromise<$models.ImportPlan> {
    return $Call.ByID(1054963909, id, dir);
}
