// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LogService is the activity log: what Otis did that did not work, and where
 * it now goes.
 * 
 * Until this existed there was nowhere. A clipboard write that failed, a
 * reveal that could not find the file manager, a watcher that stopped — each
 * went to `console.error` in a webview with no console, or to a Wails logger
 * writing to a stderr the packaged app does not have. The tree's own helper
 * said so in a comment: "There is nowhere to show it yet — the design has no
 * toast." This is the somewhere.
 * 
 * It is deliberately not a toast. A toast interrupts and then vanishes, which
 * is the wrong shape for something you want to look at *after* noticing that
 * a thing did not work — which is how these are usually noticed. The status
 * bar counts what has arrived and the popover holds the list.
 * 
 * It is in memory and per-session. A log on disk would be a second audit
 * trail with none of the care `internal/mcp`'s has (§9's 0600 file in the
 * config directory, never in the collection), and nothing here is worth that.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Clear empties the log.
 */
export function Clear(): $CancellablePromise<$models.LogEntry[] | null> {
    return $Call.ByID(1016538673);
}

/**
 * Entries returns the log, newest first.
 */
export function Entries(): $CancellablePromise<$models.LogEntry[] | null> {
    return $Call.ByID(3741864804);
}

/**
 * Record adds an entry and returns it.
 * 
 * It is exported because the *window* records through it too: a binding call
 * the window made and could not do anything about is exactly the kind of
 * failure this exists for, and having one list rather than two is the point.
 */
export function Record(level: string, source: string, message: string, detail: string): $CancellablePromise<$models.LogEntry> {
    return $Call.ByID(2069868665, level, source, message, detail);
}
