// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MCPService is the agent server as the window sees it (docs/MCP.md).
 * 
 * It is the one place `internal/mcpserver`'s four boundaries are implemented,
 * and every one of them is implemented by *delegating* to the service that
 * already owns that job: a send goes through SendService, a write through
 * RequestService or FolderService, a read through the same loaders the editor
 * uses. Nothing here reimplements an operation, which is what makes an agent's
 * write subject to the same invariants a person's is — the write guard, the
 * announcement, and `.order` left alone.
 * 
 * It is also the only thing that turns the server on, and it will not do that
 * without being asked twice: the listener and each capability are separate
 * switches, all off in the zero settings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Answer is the window's reply to a confirmation.
 */
export function Answer(id: string, approve: boolean): $CancellablePromise<void> {
    return $Call.ByID(424644296, id, approve);
}

/**
 * CopyClientBlock puts the configuration an MCP client needs on the system
 * clipboard — the same block `otis mcp config` prints.
 * 
 * **Go writes the clipboard, and the block never crosses the binding.** Two
 * reasons, and either alone would be enough.
 * 
 * The first is that it works. `navigator.clipboard.writeText` needs a secure
 * context and a user activation the webview agrees with, and Otis' window is
 * a WKWebView serving from a custom scheme: the call rejects, and the button
 * did nothing at all. Every other copy in this app already goes through
 * `app.Clipboard.SetText` for exactly this reason — CollectionService.CopyPath
 * and EnvironmentService.CopySecretValue both do.
 * 
 * The second is that the block contains a **bearer token**. Handing it to the
 * window to put on the clipboard would mean a live credential in the webview
 * whose only use was to leave again; the popover deliberately never displays
 * it. This is DESIGN-NOTES §9.12's Reveal-became-Copy applied to the one other
 * credential Otis holds.
 */
export function CopyClientBlock(): $CancellablePromise<void> {
    return $Call.ByID(465515613);
}

/**
 * Disconnect is the kill switch (§10).
 */
export function Disconnect(): $CancellablePromise<void> {
    return $Call.ByID(1886594432);
}

/**
 * SetAlwaysConfirmSends turns §4 rule 4 on or off.
 */
export function SetAlwaysConfirmSends(on: boolean): $CancellablePromise<$models.MCPStatus> {
    return $Call.ByID(803176596, on);
}

/**
 * SetCapability turns one of the three capabilities on or off.
 */
export function SetCapability(name: string, on: boolean): $CancellablePromise<$models.MCPStatus> {
    return $Call.ByID(4000234604, name, on);
}

/**
 * SetEnabled turns the listener on or off.
 */
export function SetEnabled(on: boolean): $CancellablePromise<$models.MCPStatus> {
    return $Call.ByID(2349427379, on);
}

/**
 * SetPersistAuditLog turns the audit file on or off (§9.1).
 * 
 * Turning it off keeps the session's calls in memory only. The switch exists
 * because the log is a durable record of which endpoints you asked an agent to
 * call, which is a new artifact and a real privacy trade — not as an
 * afterthought.
 */
export function SetPersistAuditLog(on: boolean): $CancellablePromise<$models.MCPStatus> {
    return $Call.ByID(1043008189, on);
}

/**
 * Status is the current state.
 */
export function Status(): $CancellablePromise<$models.MCPStatus> {
    return $Call.ByID(3221879840);
}
