// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as git$0 from "../git/models.js";

/**
 * CollectionInfo describes the collection the window is showing. The zero
 * value — an empty Path — means no collection is open, which is the state
 * screen 2b renders.
 */
export interface CollectionInfo {
    /**
     * Path is the absolute path of the collection directory.
     */
    "path": string;

    /**
     * Name is the collection's display name (collection.DisplayName).
     */
    "name": string;
}

/**
 * Node is one entry in the tree the sidebar renders.
 */
export interface Node {
    /**
     * Path is the node's collection-relative ID, "/"-separated, empty for the
     * root (docs/FORMAT.md §2.1). It is what routes carry and what the
     * expand/collapse and selection state is keyed by.
     */
    "path": string;
    "kind": NodeKind;

    /**
     * Name is the display name: a request's @name, then its "###" title, then
     * the file name; a folder's directory name.
     */
    "name": string;

    /**
     * Method is a request's HTTP method, empty when the file has no request
     * line or failed to parse.
     */
    "method"?: string;

    /**
     * GitStatus is "M", "U", "A" or "D", empty when the file is clean or not
     * in a repository.
     */
    "gitStatus"?: string;

    /**
     * Error is the parse error on a broken node.
     */
    "error"?: string;

    /**
     * Warnings are the load warnings that belong to this node, already
     * rendered for display.
     */
    "warnings"?: string[] | null;

    /**
     * Settings is a folder's _folder.http, or nil when it has none. Its
     * presence is what marks a folder as carrying shared settings.
     */
    "settings"?: Node | null;

    /**
     * Children of a folder, in display order (docs/FORMAT.md §2.2).
     */
    "children"?: Node[] | null;

    /**
     * Modified is set on a folder when any file below it is modified, so the
     * tree can show a dirty dot on a collapsed folder.
     */
    "modified"?: boolean;
}

/**
 * NodeKind discriminates the rows in the sidebar tree.
 */
export enum NodeKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * KindFolder is a directory.
     */
    KindFolder = "folder",

    /**
     * KindRequest is a *.http file that parsed.
     */
    KindRequest = "request",

    /**
     * KindFolderFile is a folder's _folder.http. It is not a tree row —
     * docs/FORMAT.md §2.1 is explicit that it is settings, not a request, and
     * `otis ls` does not list it — so it hangs off its folder's Settings
     * field rather than its Children.
     */
    KindFolderFile = "folderfile",

    /**
     * KindBroken is a *.http file that failed to parse. It is still a row and
     * still opens: seeing the parse error is the point.
     */
    KindBroken = "broken",
};

/**
 * Opened is what the window gets back when a collection is opened: which
 * collection it is, and everything needed to draw it.
 */
export interface Opened {
    "collection": CollectionInfo;
    "tree": Tree;
}

/**
 * Tree is a loaded collection and everything the sidebar needs to draw it.
 */
export interface Tree {
    "root": Node;

    /**
     * Warnings is every load warning, including those already attached to a
     * node, so a future problems view has the whole list in one place.
     */
    "warnings": Warning[] | null;

    /**
     * Git is the repository state at the moment the tree was walked. It
     * travels with the tree because a new file is untracked the instant it
     * appears, and shipping the two separately would show the tree without
     * its dots for a frame.
     */
    "git": git$0.State;
}

/**
 * Warning is a load warning, flattened for the frontend.
 */
export interface Warning {
    "path": string;
    "code": string;
    "msg": string;
}
