// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as diff$0 from "../diff/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as git$0 from "../git/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as httpclient$0 from "../httpclient/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as httpfile$0 from "../httpfile/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as resolve$0 from "../resolve/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as response$0 from "../response/models.js";

/**
 * AuthHeader describes the Authorization header @auth becomes at send time.
 * Value carries the directive's own text, so it may hold {{variables}} — it
 * is never a resolved secret.
 */
export interface AuthHeader {
    "name": string;
    "value": string;
    "kind": resolve$0.AuthKind;

    /**
     * Local is true when the @auth is in this file rather than above it.
     */
    "local": boolean;
    "source": resolve$0.Source;
}

/**
 * BodyChunk is a window of lines.
 */
export interface BodyChunk {
    "sendId": string;
    "view": response$0.ViewKind;
    "from": number;
    "lines": BodyLine[] | null;
    "total": number;
}

/**
 * BodyInfo says what the body is and how to ask for it.
 */
export interface BodyInfo {
    /**
     * Kind is "json", "xml" or "text": what the window colours it as.
     */
    "kind": response$0.Kind;

    /**
     * ContentType is the response's own header, verbatim.
     */
    "contentType": string;
    "size": number;

    /**
     * HasPretty is whether a formatted view is worth asking for. Whether it
     * succeeds is only known once it is built (a body can be labelled JSON
     * and not parse), which is what BodyView reports.
     */
    "hasPretty": boolean;

    /**
     * UTF8 is false for a binary body, which the window shows as a summary
     * rather than as text.
     */
    "utf8": boolean;
}

/**
 * BodyLine is one display line with its fold, if it opens one.
 */
export interface BodyLine {
    "text": string;

    /**
     * Fold is set on a line that opens a collapsible node.
     */
    "fold"?: response$0.Fold | null;
}

/**
 * BodyView is one rendering, described. Lines is what a virtualizer needs.
 */
export interface BodyView {
    "sendId": string;
    "view": response$0.ViewKind;
    "lines": number;
    "bytes": number;

    /**
     * Unavailable is set when this rendering does not exist — a body that is
     * not JSON after all, or one past the size where formatting is worth it.
     * It is a fact about the body, not an error, so the raw view is still
     * there and the message says which.
     */
    "unavailable"?: string;
}

/**
 * CollectionInfo describes the collection the window is showing. The zero
 * value — an empty Path — means no collection is open, which is the state
 * screen 2b renders.
 */
export interface CollectionInfo {
    /**
     * Path is the absolute path of the collection directory.
     */
    "path": string;

    /**
     * Name is the collection's display name (collection.DisplayName).
     */
    "name": string;
}

/**
 * CommitResult is the new commit and the view after it.
 */
export interface CommitResult {
    "commit": diff$0.Commit;
    "overview": diff$0.Overview;
}

/**
 * Cookie is one cookie the response set.
 */
export interface Cookie {
    "name": string;
    "value": string;
    "domain"?: string;
    "path"?: string;
    "expires"?: string;
    "maxAge"?: number;
    "secure"?: boolean;
    "httpOnly"?: boolean;
    "sameSite"?: string;
}

/**
 * Counts is the header tally screen 4a shows on the sub-tab strip. Sent is
 * what goes on the wire, so it includes the auth header and excludes anything
 * an "!inherit" switched off.
 */
export interface Counts {
    "sent": number;
    "local": number;
    "inherited": number;
}

/**
 * Document is one request file as the editor needs it: the parsed model it
 * edits, the raw text it was parsed from, and everything the file inherits
 * with the provenance of each piece.
 * 
 * The raw text travels with the model deliberately. The editor edits fields,
 * but the diff view compares text, and a file Otis cannot parse still has to
 * be openable — the raw is the escape hatch in both cases.
 */
export interface Document {
    /**
     * Path is the node's collection-relative ID (docs/FORMAT.md §2.1).
     */
    "path": string;

    /**
     * Name is the display name: @name, then the "###" title, then the file
     * name without .http.
     */
    "name": string;

    /**
     * Raw is the file's bytes as text, exactly as read.
     */
    "raw": string;

    /**
     * File is the parsed file, nil when ParseError is set.
     */
    "file": httpfile$0.File | null;

    /**
     * Index is the entry in File.Requests the editor shows: the first with a
     * request line, or 0 when the file has none.
     */
    "index": number;

    /**
     * Effective is what the request will send: headers in wire order, each
     * naming the file it came from, plus the nearest @auth (§3).
     */
    "effective": resolve$0.Effective | null;

    /**
     * Inherited is every header a folder above offered, including the ones a
     * nearer level overrode or switched off. Effective lists only what is
     * sent; this is what the Headers tab's INHERITED group draws, and it is
     * how an "!inherit" can be switched back on.
     */
    "inherited": resolve$0.Inherited[] | null;

    /**
     * InheritedAuth is the @auth the folders above declare, ignoring this
     * file's own. It is what the Auth tab shows under "Inherit from folder"
     * and what "Override for this request" is prefilled from (screen 4b).
     */
    "inheritedAuth": resolve$0.Auth | null;

    /**
     * AuthHeader is the header @auth adds at send time, or nil when no auth
     * applies. It is a row in the Headers tab, tagged AUTH (screen 4a), and
     * it counts towards Counts.Sent.
     */
    "authHeader": AuthHeader | null;

    /**
     * Counts is the "N sent · N local · N inherited" of screen 4a.
     */
    "counts": Counts;

    /**
     * Chain names every file that contributes, root-most first, this file
     * last. Its length minus one is the "1 level" of screen 4a's status bar.
     */
    "chain": string[] | null;

    /**
     * Variables is every {{name}} the request references, resolved against
     * Env, in first-use order. A secret's value is never included.
     */
    "variables": VariableRef[] | null;

    /**
     * Env is the environment the variables were resolved against, "" for none.
     */
    "env": string;

    /**
     * EnvError is set when Env could not be read, so the editor can say the
     * variables are unresolved for a reason rather than looking broken.
     */
    "envError"?: string;

    /**
     * ParseError is the parse error of an unparseable file, "" otherwise.
     * File is nil when it is set; Raw is still the file's text.
     */
    "parseError"?: string;

    /**
     * InheritError is a malformed @auth above or in this file (§3.3 makes
     * that an error, not a warning). The document still opens.
     */
    "inheritError"?: string;

    /**
     * Warnings are this file's collection warnings, already rendered.
     */
    "warnings"?: string[] | null;
}

/**
 * EnvironmentDocument is one environment open in the editor.
 */
export interface EnvironmentDocument {
    "name": string;
    "path": string;
    "active": boolean;
    "confirmBeforeSend": boolean;
    "description"?: string;
    "rows": EnvironmentRow[] | null;
    "variables": number;
    "secrets": number;

    /**
     * ReferencedBy is how many requests in the collection mention at least
     * one of this environment's variables (screen 1c's status bar). See
     * resolve.ReferencedNames for what "mention" means and why it is not the
     * same as "resolve from here".
     */
    "referencedBy": number;
    "keychain": KeychainState;
}

/**
 * EnvironmentRow is one variable in the editor's table (screen 1c).
 */
export interface EnvironmentRow {
    "name": string;

    /**
     * Value is the literal value — and is **empty for a secret**, always.
     * 
     * Not a mask: a mask is a string, and a string that sometimes holds a
     * value and sometimes holds dots is one refactor away from shipping the
     * value. The window is told Secret is true and draws the dots itself
     * (DESIGN-NOTES §8.3), so there is no path by which a resolved secret
     * value can reach it.
     */
    "value": string;
    "secret": boolean;

    /**
     * Present reports that a secret reference has a value in this machine's
     * keychain. False means a teammate committed the reference and this
     * machine has never been given the value — which the editor has to be
     * able to say, because it is the difference between "ready" and "this
     * request will fail".
     */
    "present": boolean;

    /**
     * Key is the keychain key, <collection>/<env>/<name>. It is public: the
     * design puts it on screen (screen 1c), and every part of it is already
     * committed.
     */
    "key": string;

    /**
     * Kind is the JSON shape the value is written as: a number stays a
     * number in the file.
     */
    "kind": resolve$0.EnvKind;
}

/**
 * EnvironmentSummary is one row of the environment list (screen 1c's sidebar).
 */
export interface EnvironmentSummary {
    "name": string;

    /**
     * Path is relative to the collection root, e.g. "env/staging.json".
     */
    "path": string;
    "variables": number;
    "secrets": number;
    "active": boolean;

    /**
     * ConfirmBeforeSend is the environment's own "$otis" setting
     * (docs/FORMAT.md §4.3). It is what paints the row's dot as production.
     */
    "confirmBeforeSend": boolean;
    "description"?: string;

    /**
     * ReferencedBy is how many requests in the collection mention at least
     * one of this environment's variables. See referenceCounts.
     */
    "referencedBy": number;

    /**
     * Error is the parse error for a file that could not be read. The row
     * still appears: an environment you cannot parse is exactly the one you
     * need to see in order to fix it.
     */
    "error"?: string;
}

/**
 * Environments is the whole environment surface in one payload: the list, the
 * active one, and whether this machine can reach a keychain at all.
 */
export interface Environments {
    "active": string;
    "items": EnvironmentSummary[] | null;
    "keychain": KeychainState;
}

/**
 * FailureKind classifies a send that produced no response.
 * 
 * The classes exist because the response pane renders them differently: a
 * refused connection, an unknown host and an expired certificate need
 * different things done about them, and "Error: dial tcp: ..." tells the
 * reader to go and parse a Go error themselves.
 */
export enum FailureKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * the host does not resolve
     */
    FailDNS = "dns",

    /**
     * nothing is listening
     */
    FailRefused = "refused",

    /**
     * the certificate was rejected
     */
    FailTLS = "tls",

    /**
     * @timeout expired
     */
    FailTimeout = "timeout",

    /**
     * the user stopped it
     */
    FailCancelled = "cancelled",

    /**
     * too many hops
     */
    FailRedirect = "redirect",

    /**
     * a variable or secret is missing
     */
    FailResolve = "resolve",

    /**
     * the request could not be built
     */
    FailRequest = "request",

    /**
     * any other transport failure
     */
    FailNetwork = "network",

    /**
     * the file is not a sendable request
     */
    FailCollection = "collection",
};

/**
 * KeychainState is what the window may say about the machine's credential
 * store.
 * 
 * Unavailable is a normal state, not an error (secrets.ErrUnavailable): a
 * collection whose environments reference secrets is still perfectly readable,
 * because the references are the part that is committed. The editor then shows
 * the references and says the values cannot be reached, rather than refusing.
 */
export interface KeychainState {
    "available": boolean;

    /**
     * Reason explains an unavailable keychain, in words a person can act on.
     * It never names a key's value, because there is none to name.
     */
    "reason"?: string;
}

/**
 * Node is one entry in the tree the sidebar renders.
 */
export interface Node {
    /**
     * Path is the node's collection-relative ID, "/"-separated, empty for the
     * root (docs/FORMAT.md §2.1). It is what routes carry and what the
     * expand/collapse and selection state is keyed by.
     */
    "path": string;
    "kind": NodeKind;

    /**
     * Name is the display name: a request's @name, then its "###" title, then
     * the file name; a folder's directory name.
     */
    "name": string;

    /**
     * Method is a request's HTTP method, empty when the file has no request
     * line or failed to parse.
     */
    "method"?: string;

    /**
     * GitStatus is "M", "U", "A" or "D", empty when the file is clean or not
     * in a repository.
     */
    "gitStatus"?: string;

    /**
     * Error is the parse error on a broken node.
     */
    "error"?: string;

    /**
     * Warnings are the load warnings that belong to this node, already
     * rendered for display.
     */
    "warnings"?: string[] | null;

    /**
     * Settings is a folder's _folder.http, or nil when it has none. Its
     * presence is what marks a folder as carrying shared settings.
     */
    "settings"?: Node | null;

    /**
     * Children of a folder, in display order (docs/FORMAT.md §2.2).
     */
    "children"?: Node[] | null;

    /**
     * Modified is set on a folder when any file below it is modified, so the
     * tree can show a dirty dot on a collapsed folder.
     */
    "modified"?: boolean;
}

/**
 * NodeKind discriminates the rows in the sidebar tree.
 */
export enum NodeKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * KindFolder is a directory.
     */
    KindFolder = "folder",

    /**
     * KindRequest is a *.http file that parsed.
     */
    KindRequest = "request",

    /**
     * KindFolderFile is a folder's _folder.http. It is not a tree row —
     * docs/FORMAT.md §2.1 is explicit that it is settings, not a request, and
     * `otis ls` does not list it — so it hangs off its folder's Settings
     * field rather than its Children.
     */
    KindFolderFile = "folderfile",

    /**
     * KindBroken is a *.http file that failed to parse. It is still a row and
     * still opens: seeing the parse error is the point.
     */
    KindBroken = "broken",
};

/**
 * Opened is what the window gets back when a collection is opened: which
 * collection it is, and everything needed to draw it.
 */
export interface Opened {
    "collection": CollectionInfo;
    "tree": Tree;
}

/**
 * ResponseMeta is everything about a response except the body.
 */
export interface ResponseMeta {
    "sendId": string;

    /**
     * Path is the request's node ID.
     */
    "path": string;
    "state": SendState;
    "status": string;

    /**
     * StatusCode is 0 when there was no response.
     */
    "statusCode": number;
    "proto": string;

    /**
     * Headers are the response headers in the order the server sent them
     * where Go preserves it, else sorted; duplicates are kept.
     */
    "headers": SentHeader[] | null;
    "cookies": Cookie[] | null;

    /**
     * Size is the body's length in bytes.
     */
    "size": number;

    /**
     * DurationMs is the whole exchange, including reading the body.
     */
    "durationMs": number;
    "timing": Timings;

    /**
     * At is when the response completed, for the header row's clock.
     */
    "at": string;

    /**
     * Redirects lists followed hops.
     */
    "redirects"?: httpclient$0.Redirect[] | null;
    "finalUrl": string;

    /**
     * Body describes the renderings available (see BodyInfo).
     */
    "body": BodyInfo;

    /**
     * Request is what went on the wire, masked.
     */
    "request": SentRequest;

    /**
     * Warnings are non-fatal notes from preparing the request.
     */
    "warnings"?: string[] | null;
}

/**
 * SendFailure is the events.SendError payload. It never carries a secret: the
 * message is masked, and a missing secret is named by key, never by value
 * (docs/FORMAT.md §5).
 */
export interface SendFailure {
    "sendId": string;
    "path": string;
    "kind": FailureKind;

    /**
     * Message is one line, already readable.
     */
    "message": string;

    /**
     * Detail is the longer explanation, when there is one worth showing.
     */
    "detail"?: string;

    /**
     * DurationMs is how long it took to fail.
     */
    "durationMs": number;
    "at": string;
}

/**
 * SendStarted is the events.SendStarted payload.
 */
export interface SendStarted {
    "sendId": string;
    "path": string;
    "method": string;

    /**
     * URL is masked.
     */
    "url": string;
    "at": string;

    /**
     * Env is the environment it resolved against, "" for none.
     */
    "env": string;
}

/**
 * SendState is where a send has got to.
 */
export enum SendState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SendInFlight = "in-flight",
    SendComplete = "complete",
    SendFailed = "failed",
    SendCancelled = "cancelled",
};

/**
 * SentHeader is one header as it went on the wire, masked.
 */
export interface SentHeader {
    "name": string;

    /**
     * Value has every secret the request used replaced by the mask
     * (docs/FORMAT.md §5). Masking is presentation only; the real value is
     * what was sent.
     */
    "value": string;

    /**
     * Secret is true when masking changed the value, so the window can say
     * why it is showing dots.
     */
    "secret": boolean;
}

/**
 * SentRequest is what actually went out, masked.
 * 
 * It exists so the claim the Headers tab makes is checkable: "7 sent · 4 local
 * · 3 inherited" is a prediction, and this is the record. They must agree, and
 * a test asserts they do.
 */
export interface SentRequest {
    "method": string;
    "url": string;
    "headers": SentHeader[] | null;

    /**
     * BodyBytes is the length of the body sent, after a "< ./file" body was
     * read and variables were substituted.
     */
    "bodyBytes": number;
}

/**
 * Timings is the exchange broken down, in milliseconds. Zero means "not
 * observed" — DNS and connect are zero on a reused connection.
 */
export interface Timings {
    "dnsMs": number;
    "connectMs": number;
    "tlsMs": number;
    "ttfbMs": number;
    "totalMs": number;
}

/**
 * Tree is a loaded collection and everything the sidebar needs to draw it.
 */
export interface Tree {
    "root": Node;

    /**
     * Warnings is every load warning, including those already attached to a
     * node, so a future problems view has the whole list in one place.
     */
    "warnings": Warning[] | null;

    /**
     * Git is the repository state at the moment the tree was walked. It
     * travels with the tree because a new file is untracked the instant it
     * appears, and shipping the two separately would show the tree without
     * its dots for a frame.
     */
    "git": git$0.State;
}

/**
 * VariableRef is one {{name}} the request references.
 */
export interface VariableRef {
    "name": string;

    /**
     * Origin is where the value came from: "request", "folder", "env" or
     * "builtin". Empty when the name did not resolve.
     */
    "origin"?: resolve$0.Origin;
    "source": resolve$0.Source;

    /**
     * Value is the resolved value. It is empty for a secret and for an
     * unresolved name, and a secret's value is never put here.
     */
    "value"?: string;

    /**
     * Secret marks a value that lives in the OS keychain, or a file variable
     * that resolves to one. Its value is not in this struct.
     */
    "secret"?: boolean;

    /**
     * Resolved is false for a name nothing defines. The editor styles those
     * as warnings (increment 10).
     */
    "resolved": boolean;
}

/**
 * Warning is a load warning, flattened for the frontend.
 */
export interface Warning {
    "path": string;
    "code": string;
    "msg": string;
}
