// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * OrderService writes `.order` files: the one thing that reorders a
 * collection, and the only writer of that file.
 * 
 * It is separate from CollectionService because CollectionService reads. The
 * invariant this service exists to hold is FORMAT.md §2.2's: **`.order` is
 * never rewritten except by an explicit reorder.** Adding a request, importing
 * a collection, saving a file, running a folder — none of them touch it, and
 * keeping the writer in one small file with no other callers is what makes
 * that checkable rather than hoped for.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CanUndo reports whether ⌘Z has anything to revert, so the shell can leave
 * the shortcut alone rather than offering one that refuses.
 */
export function CanUndo(): $CancellablePromise<boolean> {
    return $Call.ByID(3322879798);
}

/**
 * Mode reports whether a folder is manually ordered. nodePath is
 * collection-relative; "" is the root.
 */
export function Mode(nodePath: string): $CancellablePromise<string> {
    return $Call.ByID(511552521, nodePath);
}

/**
 * Move moves a request, folder or script into another folder at a position,
 * then writes both folders' `.order` files.
 * 
 * Both, because the entry has to leave one list and join the other: leaving it
 * out of the source's list would only put it back where alphabetical order
 * says, which is not where the drag left it. index is the position among the
 * destination's children after the move; a negative or oversized index appends.
 */
export function Move(nodePath: string, toPath: string, index: number): $CancellablePromise<$models.OrderResult> {
    return $Call.ByID(4199568319, nodePath, toPath, index);
}

/**
 * Reorder writes folder's `.order` to list nodePaths in that order.
 * 
 * nodePaths must be exactly the folder's direct children, each once: a
 * reorder writes the whole list (FORMAT.md §2.2), so a partial list would
 * leave the rest to sort alphabetically after and silently move rows the drag
 * never touched.
 */
export function Reorder(nodePath: string, nodePaths: string[] | null): $CancellablePromise<$models.OrderResult> {
    return $Call.ByID(864973057, nodePath, nodePaths);
}

/**
 * SetMode switches a folder between a manual order and alphabetical.
 * 
 * Manual writes the order the window is currently showing, so the arrangement
 * does not jump when it is turned on. Alphabetical deletes the file, which is
 * what FORMAT.md §2.2 says restores alphabetical order — and is undoable, so
 * there is no confirmation dialog in front of it: one mechanism for taking
 * back an ordering change is better than two.
 */
export function SetMode(nodePath: string, mode: string): $CancellablePromise<$models.OrderResult> {
    return $Call.ByID(1168153817, nodePath, mode);
}

/**
 * Undo reverts the last ordering change.
 * 
 * It restores the previous bytes rather than re-deriving the previous order,
 * so a hand-written `.order` comes back as it was written. It refuses when the
 * affected files no longer hold what the reorder left behind: something edited
 * them outside Otis, and overwriting that is not what ⌘Z means.
 */
export function Undo(): $CancellablePromise<$models.OrderResult> {
    return $Call.ByID(4164281904);
}
