// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RequestService reads and writes one request file.
 * 
 * It resolves against the collection CollectionService already walked, so the
 * inheritance the editor shows is computed from the same files the sidebar
 * drew. Every write goes through the write guard, or the watcher would report
 * Otis' own save as an external change.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as httpfile$0 from "../httpfile/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Create writes a new request file in folderPath and returns its node path.
 * 
 * The name is what the user typed; the file is named for its slug
 * (collection.Slug, the same rules the Postman importer uses, docs/FORMAT.md
 * §7) and the typed name is kept verbatim in an `# @name` directive, which is
 * what the tree and the tabs display (§2.1). So "Create order" becomes
 * create-order.http and still reads as "Create order" everywhere.
 * 
 * A collision gets -2, -3, and so on rather than an error: the name a person
 * types is a label, not an identifier, and two requests may reasonably want
 * the same one.
 * 
 * It does **not** touch `.order`. The new file is unlisted, so it sorts
 * alphabetically after the listed ones, and that is the whole mechanism
 * (docs/FORMAT.md §2.2). order.go stays the only writer of that file.
 */
export function Create(folderPath: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(1258686519, folderPath, name);
}

/**
 * Load reads one request file. nodePath is collection-relative; envName is the
 * active environment, or "" for none.
 * 
 * A file that does not parse is still returned, with ParseError set and Raw
 * carrying its text: seeing the error and the text is the point.
 */
export function Load(nodePath: string, envName: string): $CancellablePromise<$models.Document> {
    return $Call.ByID(932910215, nodePath, envName);
}

/**
 * Save serializes file into the request at nodePath and writes it, then
 * returns the document as it now stands on disk.
 * 
 * The Go serializer is the only writer: it produces the canonical layout of
 * docs/FORMAT.md §1.13, so a file the editor did not change is written back
 * byte for byte. Sending text from the window instead would put a second
 * formatter in the product.
 */
export function Save(nodePath: string, envName: string, file: httpfile$0.File): $CancellablePromise<$models.Document> {
    return $Call.ByID(1427003770, nodePath, envName, file);
}

/**
 * SaveText writes text to the request at nodePath verbatim, after checking
 * that it parses. It is the escape hatch for a file the structured editor
 * cannot express — a raw edit, or a repair of a file that failed to parse.
 */
export function SaveText(nodePath: string, envName: string, text: string): $CancellablePromise<$models.Document> {
    return $Call.ByID(3263052113, nodePath, envName, text);
}
