// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RequestService reads and writes one request file.
 * 
 * It resolves against the collection CollectionService already walked, so the
 * inheritance the editor shows is computed from the same files the sidebar
 * drew. Every write goes through the write guard, or the watcher would report
 * Otis' own save as an external change.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as httpfile$0 from "../httpfile/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Create writes a new request file in folderPath and returns its node path.
 * 
 * The name is what the user typed; the file is named for its slug
 * (collection.Slug, the same rules the Postman importer uses, docs/FORMAT.md
 * §7) and the typed name is kept verbatim in an `# @name` directive, which is
 * what the tree and the tabs display (§2.1). So "Create order" becomes
 * create-order.http and still reads as "Create order" everywhere.
 * 
 * A collision gets -2, -3, and so on rather than an error: the name a person
 * types is a label, not an identifier, and two requests may reasonably want
 * the same one.
 * 
 * It does **not** touch `.order`. The new file is unlisted, so it sorts
 * alphabetically after the listed ones, and that is the whole mechanism
 * (docs/FORMAT.md §2.2). order.go stays the only writer of that file.
 */
export function Create(folderPath: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(1258686519, folderPath, name);
}

/**
 * Delete removes the request at nodePath.
 * 
 * There is no confirmation parameter: unlike discarding a hunk, which is one
 * of several things the diff view's buttons do and which had to be
 * unreachable by accident, this method's name is the whole of what it does.
 * The dialog in front of it is the safety, and it says whether git still has
 * a copy.
 * 
 * It drops the entry from the folder's `.order` when one lists it, for the
 * same reason a rename rewrites the line: a `.order` naming a file that is not
 * there produces a warning on every walk (docs/FORMAT.md §2.2), and the user
 * did not leave it behind — Otis did.
 */
export function Delete(nodePath: string): $CancellablePromise<void> {
    return $Call.ByID(976101836, nodePath);
}

/**
 * Duplicate copies the request at nodePath into the same folder and returns
 * the copy's node path.
 * 
 * The copy is "<name> copy", and "<name> copy 2" if that is taken, with the
 * file named for the slug of whichever it settled on — so the label in the
 * tree and the name on disk never disagree, however many times it is used.
 * 
 * Like Create it does not touch `.order`: the copy is unlisted and sorts
 * alphabetically after the listed entries, which is the whole mechanism
 * (docs/FORMAT.md §2.2).
 */
export function Duplicate(nodePath: string): $CancellablePromise<string> {
    return $Call.ByID(4095449744, nodePath);
}

/**
 * Load reads one request file. nodePath is collection-relative; envName is the
 * active environment, or "" for none.
 * 
 * A file that does not parse is still returned, with ParseError set and Raw
 * carrying its text: seeing the error and the text is the point.
 */
export function Load(nodePath: string, envName: string): $CancellablePromise<$models.Document> {
    return $Call.ByID(932910215, nodePath, envName);
}

/**
 * Rename gives the request at nodePath a new name and returns its new node
 * path, which the caller navigates to.
 * 
 * It changes both halves of a request's identity, and does so together: the
 * `# @name` directive becomes what was typed, and the file is renamed to that
 * name's slug. That is deliberate symmetry with Create, which writes both from
 * one typed name for the same reason — the file name and the tree label are
 * two views of the same thing, and a rename that moved only one of them would
 * leave a `place-order.http` called "Create order" that nobody meant. The
 * dialog shows both lines before it happens (DESIGN-NOTES §8.2).
 * 
 * A file that did not parse is refused rather than renamed, because half of
 * this operation is rewriting its contents and Otis does not rewrite a file it
 * could not read — the same stance the folder settings editor takes.
 * 
 * It keeps `.order` in step, and only in step: if the folder has one and the
 * entry is listed, that one line is rewritten so the request stays where it
 * was. A folder with no `.order` does not acquire one.
 */
export function Rename(nodePath: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(2984554981, nodePath, name);
}

/**
 * Save serializes file into the request at nodePath and writes it, then
 * returns the document as it now stands on disk.
 * 
 * The Go serializer is the only writer: it produces the canonical layout of
 * docs/FORMAT.md §1.13, so a file the editor did not change is written back
 * byte for byte. Sending text from the window instead would put a second
 * formatter in the product.
 */
export function Save(nodePath: string, envName: string, file: httpfile$0.File): $CancellablePromise<$models.Document> {
    return $Call.ByID(1427003770, nodePath, envName, file);
}

/**
 * SaveText writes text to the request at nodePath verbatim, after checking
 * that it parses. It is the escape hatch for a file the structured editor
 * cannot express — a raw edit, or a repair of a file that failed to parse.
 */
export function SaveText(nodePath: string, envName: string, text: string): $CancellablePromise<$models.Document> {
    return $Call.ByID(3263052113, nodePath, envName, text);
}
