// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RequestService reads and writes one request file.
 * 
 * It resolves against the collection CollectionService already walked, so the
 * inheritance the editor shows is computed from the same files the sidebar
 * drew. Every write goes through the write guard, or the watcher would report
 * Otis' own save as an external change.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as httpfile$0 from "../httpfile/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Load reads one request file. nodePath is collection-relative; envName is the
 * active environment, or "" for none.
 * 
 * A file that does not parse is still returned, with ParseError set and Raw
 * carrying its text: seeing the error and the text is the point.
 */
export function Load(nodePath: string, envName: string): $CancellablePromise<$models.Document> {
    return $Call.ByID(932910215, nodePath, envName);
}

/**
 * Save serializes file into the request at nodePath and writes it, then
 * returns the document as it now stands on disk.
 * 
 * The Go serializer is the only writer: it produces the canonical layout of
 * docs/FORMAT.md §1.13, so a file the editor did not change is written back
 * byte for byte. Sending text from the window instead would put a second
 * formatter in the product.
 */
export function Save(nodePath: string, envName: string, file: httpfile$0.File): $CancellablePromise<$models.Document> {
    return $Call.ByID(1427003770, nodePath, envName, file);
}

/**
 * SaveText writes text to the request at nodePath verbatim, after checking
 * that it parses. It is the escape hatch for a file the structured editor
 * cannot express — a raw edit, or a repair of a file that failed to parse.
 */
export function SaveText(nodePath: string, envName: string, text: string): $CancellablePromise<$models.Document> {
    return $Call.ByID(3263052113, nodePath, envName, text);
}
