// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ScriptService loads and writes the `.js` files in a collection, and is the
 * only thing that writes one.
 * 
 * Separate from RequestService for the reason every writer in this package is
 * separate: "does anything else write this kind of file?" should be a question
 * answered by reading one file. A `.js` is not a `.http` — nothing parses it,
 * nothing serializes it, and the round-trip guarantee of docs/FORMAT.md §1.13
 * has nothing to say about it. **The text is written verbatim**: Otis has no
 * opinion about JavaScript formatting and adding one would put every
 * colleague's prettier config in somebody's diff.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Load reads the script at nodePath.
 */
export function Load(nodePath: string): $CancellablePromise<$models.ScriptDocument> {
    return $Call.ByID(2097008367, nodePath);
}

/**
 * Save writes text to the script at nodePath and returns it as it now stands.
 * 
 * Verbatim, byte for byte. The window sends what the editor holds and Go
 * writes it: there is no serializer in the path because there is nothing to
 * serialize, which also means a script cannot be reformatted by saving it.
 */
export function Save(nodePath: string, text: string): $CancellablePromise<$models.ScriptDocument> {
    return $Call.ByID(540054754, nodePath, text);
}
