// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ScriptService loads and writes the `.js` files in a collection, and is the
 * only thing that writes one.
 * 
 * Separate from RequestService for the reason every writer in this package is
 * separate: "does anything else write this kind of file?" should be a question
 * answered by reading one file. A `.js` is not a `.http` — nothing parses it,
 * nothing serializes it, and the round-trip guarantee of docs/FORMAT.md §1.13
 * has nothing to say about it. **The text is written verbatim**: Otis has no
 * opinion about JavaScript formatting and adding one would put every
 * colleague's prettier config in somebody's diff.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Create writes a new script and returns its node path.
 * 
 * The starter text is one comment line saying what runs it, and this is the
 * only time Otis writes into a `.js` at all — Save is verbatim and always
 * will be. A line naming what runs a file is worth having for the colleague
 * who meets it in a terminal rather than in this window, and it is a fact
 * about the file name rather than an opinion about JavaScript.
 */
export function Create(req: $models.NewScript): $CancellablePromise<string> {
    return $Call.ByID(1706581023, req);
}

/**
 * Load reads the script at nodePath.
 */
export function Load(nodePath: string): $CancellablePromise<$models.ScriptDocument> {
    return $Call.ByID(2097008367, nodePath);
}

/**
 * Plan reports the file a NewScript would create and the sentence that says
 * what runs it, without creating anything.
 * 
 * It exists so the dialog can show both while you are still choosing — the
 * same promise the create dialog makes for a request (DESIGN-NOTES §8.2) —
 * and it is Go's answer rather than a mirror in the window, because the
 * naming rule is §2.4's and there must be one implementation of it.
 */
export function Plan(req: $models.NewScript): $CancellablePromise<$models.ScriptPlan> {
    return $Call.ByID(658723216, req);
}

/**
 * Save writes text to the script at nodePath and returns it as it now stands.
 * 
 * Verbatim, byte for byte. The window sends what the editor holds and Go
 * writes it: there is no serializer in the path because there is nothing to
 * serialize, which also means a script cannot be reformatted by saving it.
 */
export function Save(nodePath: string, text: string): $CancellablePromise<$models.ScriptDocument> {
    return $Call.ByID(540054754, nodePath, text);
}
