// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SendService sends requests and holds what came back.
 * 
 * The response body never crosses the binding whole: it stays in a
 * response.Document here and the window asks for the lines it is about to
 * draw. Sending itself is asynchronous — Send returns an id at once and the
 * outcome arrives as an event — because a send can take thirty seconds and a
 * binding call that blocks for thirty seconds blocks the window.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as resolve$0 from "../resolve/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as response$0 from "../response/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Cancel stops a send in flight. Cancelling one that has already finished is
 * not an error: the click and the response can cross.
 */
export function Cancel(sendID: string): $CancellablePromise<void> {
    return $Call.ByID(443654568, sendID);
}

/**
 * ClearSessionScope forgets one folder's or one environment's session
 * variables.
 */
export function ClearSessionScope(scope: resolve$0.SessionScope, owner: string): $CancellablePromise<void> {
    return $Call.ByID(3917222771, scope, owner);
}

/**
 * ClearSessionVars forgets every session variable.
 */
export function ClearSessionVars(): $CancellablePromise<void> {
    return $Call.ByID(4196778175);
}

/**
 * CopyAsCurl puts the request on the clipboard as a `curl` command.
 * 
 * # Why the sender and not the editor
 * 
 * What is worth copying is the request as it will actually be *sent*:
 * inherited headers, the environment's values, the `Authorization` an
 * `@auth` line becomes. A command built from the file would carry
 * `{{baseUrl}}` and none of the inheritance, which is a command that does not
 * run and a lie about what Otis does.
 * 
 * # Secrets
 * 
 * `withSecrets` is a decision only the caller can make, so it is a parameter
 * and not a policy here. Masked, the command is safe to paste into an issue
 * and will not run; unmasked it runs and carries a credential. Both are
 * legitimate and the window offers them as two separate items, so the choice
 * is made by the person, in words, at the moment they make it.
 * 
 * The value goes to the clipboard **from Go** and never crosses the binding
 * (CLAUDE.md), which is the same path `EnvironmentService.CopySecretValue`
 * takes and for the same reason.
 * 
 * Scripts do not run. A pre-request hook can change the request, so a command
 * built without running one can differ from what a send would produce — but
 * running somebody's script as a side effect of a copy is worse, and a hook
 * may write session variables or hit the network through nothing at all.
 * Where there is one, the command says so in a comment.
 */
export function CopyAsCurl(nodePath: string, envName: string, withSecrets: boolean): $CancellablePromise<void> {
    return $Call.ByID(2969851553, nodePath, envName, withSecrets);
}

/**
 * Discard frees a response's body. The window calls it when the tab that was
 * showing it closes.
 */
export function Discard(sendID: string): $CancellablePromise<void> {
    return $Call.ByID(2875736508, sendID);
}

/**
 * Lines returns count display lines starting at from, with the folds that open
 * inside them. It is how the body reaches the window: a viewport at a time.
 */
export function Lines(sendID: string, view: response$0.ViewKind, $from: number, count: number): $CancellablePromise<$models.BodyChunk> {
    return $Call.ByID(695443057, sendID, view, $from, count);
}

/**
 * Meta returns a finished send's metadata, for a window that reconnected or
 * re-rendered after the event went by.
 */
export function Meta(sendID: string): $CancellablePromise<$models.ResponseMeta> {
    return $Call.ByID(2288358359, sendID);
}

/**
 * RunFolder sends every request below a folder, one at a time, in the folder's
 * display order — which is `.order` where there is one and alphabetical where
 * there is not (docs/FORMAT.md §2.2).
 * 
 * One at a time, deliberately: the requests in a folder are usually a sequence
 * (create an order, then read it back), a post-response script sets the
 * variable the next request references, and they share one cookie jar. Running
 * them in parallel would make the outcome depend on scheduling.
 * 
 * It answers with the run's id immediately and reports itself over events:
 * events.RunStarted with the whole plan, events.RunResult per request as it
 * finishes, and events.RunComplete with the summary. Each request also emits
 * its own send events, so the response pane fills in as the run goes.
 */
export function RunFolder(nodePath: string, envName: string, stopOnFailure: boolean): $CancellablePromise<string> {
    return $Call.ByID(3357851903, nodePath, envName, stopOnFailure);
}

/**
 * Send starts sending the request at nodePath against envName ("" for none)
 * and returns the send's id immediately.
 * 
 * Everything after this point arrives as an event keyed by that id:
 * events.SendStarted, then events.SendComplete or events.SendError. The id is
 * the window's handle on the send — it is what Cancel takes and what the body
 * calls take.
 */
export function Send(nodePath: string, envName: string): $CancellablePromise<string> {
    return $Call.ByID(3168637144, nodePath, envName);
}

/**
 * SessionScope returns the variables a run set for one scope and owner: a
 * folder's node ID, or an environment's name (docs/FORMAT.md §4.5).
 * 
 * It is what the folder view's Session group lists, which has to be the
 * folder's own values and not the collection's — a group headed "this
 * machine only" that showed somebody else's folder's variables would be
 * answering a different question from the one it asks.
 */
export function SessionScope(scope: resolve$0.SessionScope, owner: string): $CancellablePromise<resolve$0.SessionValue[] | null> {
    return $Call.ByID(915136890, scope, owner);
}

/**
 * SessionVars returns the variables runs have set, read-only.
 * 
 * Read-only on purpose: they are set by a run, and the only writes the window
 * gets are Clear and ClearScope. There is no setter here for the same reason
 * there is no secret getter — the value's whole contract is where it can and
 * cannot go (docs/FORMAT.md §4.5).
 */
export function SessionVars(): $CancellablePromise<resolve$0.SessionValue[] | null> {
    return $Call.ByID(2934514408);
}

/**
 * View describes one rendering of a body, building it if this is the first
 * call. Formatting a large body happens here, on the binding's goroutine and
 * not on the window's, which is the point.
 */
export function View(sendID: string, view: response$0.ViewKind): $CancellablePromise<$models.BodyView> {
    return $Call.ByID(131349747, sendID, view);
}
