// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService is the frontend's only durable storage. The frontend is
 * forbidden from touching localStorage or sessionStorage, so pane sizes, open
 * tabs and recent collections all round-trip through here to a JSON file in
 * the OS config directory.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "../settings/models.js";

/**
 * Get returns the persisted settings. A missing or unreadable file yields the
 * zero value rather than an error; see the settings package.
 */
export function Get(): $CancellablePromise<settings$0.Settings> {
    return $Call.ByID(2180063471);
}

/**
 * RemoveRecent drops one entry from the recent-collections list and returns
 * the settings as they now stand.
 */
export function RemoveRecent(path: string): $CancellablePromise<settings$0.Settings> {
    return $Call.ByID(1632136766, path);
}

/**
 * SetPanes records the pane geometry.
 * 
 * There is deliberately no method that writes the whole document. Go and the
 * window both write these settings — Go owns the recents list and the last
 * collection, the window owns the panes and the tabs — and a whole-document
 * write from one side silently discards whatever the other side wrote in the
 * meantime. Every setter here is a read-modify-write of its own fields.
 */
export function SetPanes(panes: settings$0.Panes): $CancellablePromise<void> {
    return $Call.ByID(1372986714, panes);
}

/**
 * SetTabs records the open document tabs and which one is active.
 */
export function SetTabs(tabs: settings$0.Tabs): $CancellablePromise<void> {
    return $Call.ByID(1113374883, tabs);
}
