// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * StartService is the two ways a collection comes into being that are not
 * opening one that already exists: screen 2b's "Start fresh" and "Clone
 * repository" cards, which shipped as `soon` because neither was in the A–E
 * plan (DESIGN-NOTES §9.9).
 * 
 * Both end the same way — a directory exists, and it is now the open
 * collection — which is why they are one service rather than two, and why
 * neither of them opens it themselves: `CollectionService` is the only thing
 * that decides what "open" means, and this hands it a path exactly as the
 * Postman import does.
 * 
 * What it deliberately does not do is **`git init`**. Screen 2b's example line
 * for Start fresh reads `mkdir .requests && git init`, and the first half of
 * that is this service. The second half is not: `internal/git` is read-only
 * and `internal/diff` is the only thing in Otis that writes to a repository,
 * and creating one would be a third writer with no review in front of it. A
 * collection made inside a repository is already versioned, which is the
 * common case; one made outside is a directory of files, which docs/VISION.md
 * says is a perfectly good thing to be until somebody runs `git init`
 * themselves.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelClone stops the clone in flight, if there is one. Doing nothing is a
 * normal outcome: the dialog's Cancel does not know whether git has already
 * finished.
 */
export function CancelClone(): $CancellablePromise<void> {
    return $Call.ByID(407985537);
}

/**
 * ChooseLocation shows the native directory picker for where a new collection
 * should be created or cloned.
 * 
 * Cancelling returns "" with no error, like every other picker here.
 */
export function ChooseLocation(): $CancellablePromise<string> {
    return $Call.ByID(1432409352);
}

/**
 * Clone clones url into parent/name and opens the collection inside it.
 * 
 * Progress is emitted as events.CloneProgress, one event per line git writes,
 * because a clone of anything real takes long enough that a dialog with no
 * output in it looks hung. Nothing else is done with git's output: it is not
 * logged, not kept, and not parsed except to find the sentence that explains a
 * failure.
 */
export function Clone(url: string, parent: string, name: string): $CancellablePromise<$models.StartResult> {
    return $Call.ByID(2625091027, url, parent, name);
}

/**
 * Create writes a new collection into parent/name and opens it.
 */
export function Create(parent: string, name: string): $CancellablePromise<$models.StartResult> {
    return $Call.ByID(1451393586, parent, name);
}

/**
 * Defaults answers what the dialogs need to open.
 */
export function Defaults(): $CancellablePromise<$models.StartDefaults> {
    return $Call.ByID(4248804152);
}

/**
 * SuggestName is the folder name a clone URL implies — git's own rule, so the
 * dialog can show the path before anything runs.
 */
export function SuggestName(url: string): $CancellablePromise<string> {
    return $Call.ByID(2538455751, url);
}
