package events

import (
	"bytes"
	"fmt"
)

// TypeScript renders the registry as the contents of
// frontend/src/lib/events.gen.ts.
func TypeScript() []byte {
	var b bytes.Buffer
	b.WriteString("// Generated by internal/events/gen from internal/events/names.go.\n")
	b.WriteString("// DO NOT EDIT. Run `go generate ./internal/events` after changing the Go side.\n")
	b.WriteString("//\n")
	b.WriteString("// Event names are never written as literals: Go uses the constants in\n")
	b.WriteString("// internal/events, TypeScript uses this object.\n\n")
	b.WriteString("export const OtisEvent = {\n")
	for _, e := range Registry {
		fmt.Fprintf(&b, "  /** %s */\n", e.Doc)
		fmt.Fprintf(&b, "  %s: %q,\n", e.Ident, e.Name)
	}
	b.WriteString("} as const;\n\n")
	b.WriteString("export type OtisEventName = (typeof OtisEvent)[keyof typeof OtisEvent];\n")
	return b.Bytes()
}
