// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Change is one row of the changes list.
 */
export interface Change {
    /**
     * Path is collection-relative, "/"-separated (docs/FORMAT.md §2.1).
     */
    "path": string;

    /**
     * OldPath is where a renamed file came from, else "".
     */
    "oldPath"?: string;
    "status": Status;
    "adds": number;
    "dels": number;

    /**
     * Staged and Unstaged say which halves exist, so a partly staged file
     * can say so rather than looking like either one.
     */
    "staged": boolean;
    "unstaged": boolean;

    /**
     * Hunks is how many hunks the file has, so the list agrees with the
     * footer before the file is opened.
     */
    "hunks": number;

    /**
     * Binary or oversized: a change with no reviewable diff.
     */
    "binary"?: boolean;
}

/**
 * Commit is a commit as the view names one.
 */
export interface Commit {
    "hash": string;
    "short": string;
    "subject": string;
    "author": string;
    "when": string;
}

/**
 * FileDiff is one file's diff, working tree against HEAD.
 */
export interface FileDiff {
    "path": string;
    "oldPath"?: string;
    "status": Status;
    "adds": number;
    "dels": number;
    "hunks": Hunk[] | null;
    "binary"?: boolean;

    /**
     * Note explains a file with no hunks that is nonetheless changed.
     */
    "note"?: string;
}

/**
 * Hunk is a run of changes with its surrounding context.
 */
export interface Hunk {
    "oldStart": number;
    "oldLines": number;
    "newStart": number;
    "newLines": number;

    /**
     * Label is the semantic header, when one can be derived: the request
     * line for a hunk in the body, "tests" for one in a post-response
     * script (see label.go). Empty means the view falls back to the raw
     * "@@ -a,b +c,d @@" offsets.
     */
    "label"?: string;
    "lines": Line[] | null;
    "adds": number;
    "dels": number;

    /**
     * Staged reports that this hunk is already in the index: it came from
     * the HEAD-to-index diff rather than the index-to-worktree one.
     */
    "staged": boolean;
}

/**
 * Line is one line of a hunk.
 * 
 * It carries both line numbers because the design draws both gutters, in
 * unified *and* split view (DESIGN-NOTES §4.6: two 44px gutters). The number
 * that does not apply is zero, which is what lets the split view leave a cell
 * blank rather than guess.
 */
export interface Line {
    "kind": LineKind;
    "text": string;

    /**
     * Old is the 1-based line number on the old side, 0 for an added line.
     */
    "old": number;

    /**
     * New is the 1-based line number on the new side, 0 for a removed line.
     */
    "new": number;
}

/**
 * LineKind is what a diff line is.
 */
export enum LineKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * Context is a line both sides share.
     */
    Context = " ",

    /**
     * Added is a line only the new side has.
     */
    Added = "+",

    /**
     * Removed is a line only the old side has.
     */
    Removed = "-",
};

/**
 * Overview is the whole diff view's left-hand side.
 */
export interface Overview {
    /**
     * Repository is false when the collection is not in a git repository,
     * which is a normal state and one of the view's empty cases.
     */
    "repository": boolean;
    "branch": string;
    "head": string;
    "detached": boolean;
    "changes": Change[] | null;

    /**
     * LastCommit is nil in a repository with no commits yet.
     */
    "lastCommit"?: Commit | null;

    /**
     * Adds, Dels and Hunks total the changes, which is what the status bar
     * shows ("+4 −2 · 2 hunks").
     */
    "adds": number;
    "dels": number;
    "hunks": number;

    /**
     * CanCommit is false when git has no identity configured, in which case
     * Reason says so: a commit would fail, and saying why up front beats
     * failing on the button.
     */
    "canCommit": boolean;
    "reason"?: string;
}

/**
 * Status is a file's state, as the one letter the changes list shows.
 */
export enum Status {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * StatusModified is git's M: tracked and changed.
     */
    StatusModified = "M",

    /**
     * StatusAdded is a file staged for addition.
     */
    StatusAdded = "A",

    /**
     * StatusDeleted is git's D.
     */
    StatusDeleted = "D",

    /**
     * StatusUntracked is a file git does not know about yet.
     */
    StatusUntracked = "U",

    /**
     * StatusRenamed is a file that moved. git reports an unstaged move as a
     * delete plus an untracked file; Otis pairs them back up, because "this
     * request moved into orders/" is the change that actually happened.
     */
    StatusRenamed = "R",
};
