// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Collection is a loaded tree plus the warnings raised while loading it.
 */
export interface Collection {
    "root": Node | null;
    "warnings"?: Warning[] | null;
}

/**
 * Kind distinguishes folders from requests.
 */
export enum Kind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    KindFolder = "folder",
    KindRequest = "request",

    /**
     * KindScript is a *.js file. It is a tree row because it is a file in the
     * collection that changes what requests do, and a file that changes
     * behaviour while staying invisible is the thing this product exists to
     * argue against.
     */
    KindScript = "script",
};

/**
 * Node is a folder or a request in the collection tree.
 */
export interface Node {
    /**
     * ID is the path relative to the collection root, "/"-separated, with
     * no trailing slash. It is stable across reloads. The root has ID "".
     */
    "id": string;
    "kind": Kind;

    /**
     * Name is the display name: for requests the @name directive, then the
     * "###" title, then the file name without extension; for folders the
     * directory name.
     */
    "name": string;

    /**
     * Method is the HTTP method label of a request node ("" if broken or
     * if the file has no request line).
     */
    "method"?: string;

    /**
     * Hook is set on a KindScript node that runs automatically — a folder's
     * _pre.js or _post.js, or a request's <name>.pre.js or <name>.post.js.
     * A script that is not a hook is a plain ES module: nothing runs it
     * unless a hook imports it (docs/FORMAT.md §2.4).
     */
    "hook"?: boolean;

    /**
     * HookOf is the node ID of the request a request-level hook belongs to,
     * or "" for a folder hook and for a module.
     */
    "hookOf"?: string;

    /**
     * Broken is set when the file failed to parse. The node still appears.
     */
    "broken"?: boolean;
    "error"?: string;

    /**
     * Children of a folder, in display order.
     */
    "children"?: (Node | null)[] | null;
}

/**
 * Warning is a non-fatal problem found while loading.
 */
export interface Warning {
    /**
     * Path is relative to the collection root, "/"-separated.
     */
    "path": string;
    "code": WarningCode;
    "msg": string;
}

/**
 * WarningCode identifies the kind of warning.
 */
export enum WarningCode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * file failed to parse; node marked broken
     */
    WarnParseError = "parse-error",

    /**
     * more than one request in a file
     */
    WarnMultipleRequests = "multiple-requests",

    /**
     * request file without a request line
     */
    WarnNoRequestLine = "no-request-line",

    /**
     * _folder.http contains a request line
     */
    WarnFolderHasRequest = "folder-has-request",

    /**
     * .order names an entry that does not exist
     */
    WarnOrderMissing = "order-missing",

    /**
     * .order repeats an entry
     */
    WarnOrderDuplicate = "order-duplicate",

    /**
     * directory or file could not be read
     */
    WarnUnreadable = "unreadable",
};
