// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AuditDecision is what happened to a tool call.
 * 
 * It is not mcp.Outcome. Outcome is what the policy *decided* before anyone
 * was asked — proceed, confirm, deny — and this is how the call actually
 * ended, which is the only thing worth recording. A call the policy sent to a
 * confirmation can still end refused, timed-out or confirmed, and a log that
 * stored the policy's answer could not tell those apart.
 */
export enum AuditDecision {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * Allowed: policy let it through with nobody asked.
     */
    Allowed = "allowed",

    /**
     * Confirmed: a person was asked and said yes.
     */
    Confirmed = "confirmed",

    /**
     * Refused: a person was asked and said no.
     */
    Refused = "refused",

    /**
     * DeniedByPolicy: never reached a person.
     */
    DeniedByPolicy = "denied-by-policy",

    /**
     * TimedOut: a person was asked and did not answer.
     */
    TimedOut = "timed-out",

    /**
     * RateLimited: refused by §10's limiter.
     */
    RateLimited = "rate-limited",

    /**
     * Asked: a person was asked through their client and the answer has not
     * come back yet.
     * 
     * It exists because the protocol's confirmation is a round trip rather
     * than a blocking call (§6.3): the tool returns "input required", the
     * client collects the answer, and the retry produces the line that says
     * what happened. Without this, the asking would leave no trace at all
     * and an agent putting prompts in front of somebody who never answers
     * would be invisible in the log.
     */
    Asked = "asked",
};

/**
 * AuditSurface is where the person was actually asked.
 * 
 * Also not mcp.Surface. That one is a *constraint* the policy places on a
 * call — "this may only be confirmed in the window" — and this is where the
 * asking happened. Recording the second is what makes §6.4 checkable after
 * the fact: a call the policy marked window-only that was logged as confirmed
 * on the client is a bug you can find in the log.
 */
export enum AuditSurface {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * OnClient: the MCP client asked, by elicitation.
     */
    OnClient = "client",

    /**
     * InWindow: Otis' own window asked.
     */
    InWindow = "window",

    /**
     * NotAsked is for a call nobody was asked about — allowed, denied by
     * policy, or rate-limited.
     */
    NotAsked = "",
};

/**
 * An Entry is one line of the log.
 * 
 * Every field here is a name, a code or a duration. Nothing in this struct can
 * hold a payload, and nothing may be added to it that can: the test in
 * audit_test.go drives real sends with real secrets past it and fails if any
 * value, body or header reaches a line.
 */
export interface Entry {
    /**
     * At is when, in UTC.
     */
    "at": string;

    /**
     * Collection is the open collection's directory name. Without it a log
     * spanning two collections cannot say which orders/create-order.http was
     * touched. The name, not the absolute path — the path is on this machine
     * and adds nothing the name does not.
     */
    "collection": string;

    /**
     * Tool is the tool's name.
     */
    "tool": string;

    /**
     * Target is the node path of the request or folder, never a URL. A URL
     * can carry a credential in a query parameter; a node path cannot carry
     * anything that was not already committed to the repository.
     */
    "target"?: string;

    /**
     * Environment is the environment's name, or "" for none.
     */
    "environment": string;

    /**
     * Surface is where the person was asked.
     */
    "surface": AuditSurface;

    /**
     * Decision is how the call ended.
     */
    "decision": AuditDecision;

    /**
     * Status is an HTTP status code, a failure kind, or "created"/"modified"
     * for a write. A short code, never a message: a message is free text and
     * free text is where a URL, and then a query parameter, and then a
     * credential ends up.
     */
    "status"?: string;

    /**
     * DurationMs is how long the call took.
     */
    "durationMs": number;

    /**
     * Client is the MCP client's declared name and version.
     */
    "client"?: string;
}
