// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as git$0 from "../../../../otis-http/otis/internal/git/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as services$0 from "../../../../otis-http/otis/internal/services/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "app:ready": string;
            "collection:changed": services$0.Tree;
            "collection:opened": services$0.CollectionInfo;
            "environments:changed": services$0.Environments;
            "git:changed": git$0.State;
            "send:complete": services$0.ResponseMeta;
            "send:error": services$0.SendFailure;
            "send:started": services$0.SendStarted;
            "session-vars:changed": void;
            "settings:changed": void;
        }
    }
}
