// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConsoleLine is one captured console call.
 */
export interface ConsoleLine {
    /**
     * Level is "log", "info", "warn", "error" or "debug".
     */
    "level": string;

    /**
     * Text is the arguments joined by a space, already masked.
     */
    "text": string;

    /**
     * Path is the script the call came from.
     */
    "path"?: string;
    "at": string;
}

/**
 * TestResult is one test's outcome (docs/FORMAT.md §9.9).
 */
export interface TestResult {
    /**
     * Index is the test's position in the phase, so a streamed result can
     * fill in a row the window already drew.
     */
    "index": number;
    "name": string;

    /**
     * Passed is false when the function threw.
     */
    "passed": boolean;

    /**
     * Message is the failure, already masked. Empty on a pass.
     */
    "message"?: string;

    /**
     * Path is the script the test was declared in.
     */
    "path"?: string;
    "durationMs": number;
}
