// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Redirect is one followed hop.
 */
export interface Redirect {
    /**
     * URL is the address that answered with a redirect.
     */
    "url": string;
    "statusCode": number;

    /**
     * Location is where it pointed.
     */
    "location": string;
}
