// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Auth is an effective @auth value with provenance. String fields may still
 * contain {{variables}}.
 */
export interface Auth {
    "kind": AuthKind;
    "token"?: string;
    "username"?: string;
    "password"?: string;

    /**
     * AWS fields (Kind == AuthAWS). Either Profile or AccessKey/SecretKey
     * is set, never both. Region and Service are optional here; the sender
     * derives them from the profile and the host when empty.
     */
    "profile"?: string;
    "accessKey"?: string;
    "region"?: string;
    "service"?: string;
    "source": Source;
}

/**
 * AuthKind is the scheme of an @auth directive.
 */
export enum AuthKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AuthBearer = "bearer",
    AuthBasic = "basic",

    /**
     * AuthAWS signs the request with AWS Signature Version 4.
     */
    AuthAWS = "aws",

    /**
     * AuthNone is an explicit opt-out: no auth is sent even if a folder
     * above defines one. It is distinct from Effective.Auth == nil, which
     * means nothing was declared anywhere.
     */
    AuthNone = "none",
};

/**
 * Disabled records a header removed by "!inherit".
 */
export interface Disabled {
    "name": string;

    /**
     * Source is the "!inherit" line.
     */
    "source": Source;

    /**
     * Removed are the inherited headers that the marker suppressed. It is
     * empty when nothing above defined the header.
     */
    "removed"?: Header[] | null;
}

/**
 * Effective is the result of walking _folder.http files from the root down
 * to a request.
 */
export interface Effective {
    /**
     * Headers in send order: outermost folder first, request last. A header
     * overridden at a nearer level appears once, at the nearer level's
     * position.
     */
    "headers": Header[] | null;

    /**
     * Disabled lists "!inherit" markers encountered, nearest last.
     */
    "disabled"?: Disabled[] | null;

    /**
     * Auth is the nearest @auth directive, or nil if none was declared.
     */
    "auth"?: Auth | null;
}

/**
 * Header is an effective header with provenance.
 */
export interface Header {
    "name": string;
    "value": string;
    "source": Source;
}

/**
 * HeaderState is the fate of a header an ancestor folder contributed.
 */
export enum HeaderState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * HeaderSent means the header is in the effective set and goes on the wire.
     */
    HeaderSent = "sent",

    /**
     * HeaderOverridden means a nearer level defined the same name, so this
     * value is replaced (docs/FORMAT.md §3.1: override is total).
     */
    HeaderOverridden = "overridden",

    /**
     * HeaderOff means a nearer level wrote "!inherit" for the name, so
     * nothing of it is sent (§3.2).
     */
    HeaderOff = "off",
};

/**
 * Inherited is one header an ancestor folder contributed, with what became
 * of it. Effective.Headers lists only what is sent; this lists everything a
 * folder above offered, so the UI can show an inherited header that was
 * overridden or switched off — and switch it back on.
 */
export interface Inherited {
    "name": string;
    "value": string;
    "source": Source;
    "state": HeaderState;

    /**
     * By is the level that overrode or disabled the header. It is nil when
     * State is HeaderSent.
     */
    "by"?: Source | null;
}

/**
 * Origin says which scope a variable value came from.
 */
export enum Origin {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * @var in the request file
     */
    OriginRequest = "request",

    /**
     * @var in a _folder.http
     */
    OriginFolder = "folder",

    /**
     * env/<name>.json
     */
    OriginEnv = "env",

    /**
     * {{$uuid}} and friends
     */
    OriginBuiltin = "builtin",
};

/**
 * Source identifies where a resolved value was defined.
 */
export interface Source {
    /**
     * Path is relative to the collection root, e.g. "users/_folder.http"
     * or "users/create.http".
     */
    "path": string;
    "line"?: number;
}
