// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConfirmKind discriminates the two things that ask a person.
 */
export enum ConfirmKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * ConfirmSend is a request about to go on the wire.
     */
    ConfirmSend = "send",

    /**
     * ConfirmSession is a session variable about to be set (§8.1).
     */
    ConfirmSession = "session",
};
