// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Fold is a collapsible node: the line that opens a container, the line that
 * closes it, and how many direct children it has (screen 1a's "2 items" chip).
 * Fields are int32 for the same reason View's offsets are: a large body has
 * hundreds of thousands of folds, and 32 bytes each is more memory than the
 * text they describe.
 */
export interface Fold {
    /**
     * Line is the 0-based line the container opens on.
     */
    "line": number;

    /**
     * End is the 0-based line it closes on.
     */
    "end": number;

    /**
     * Count is the number of direct children.
     */
    "count": number;

    /**
     * Object is true for "{", false for "[".
     */
    "object": boolean;
}

/**
 * Kind is the body's structure, which decides whether a pretty view exists and
 * how the window colours it.
 */
export enum Kind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    KindJSON = "json",
    KindXML = "xml",
    KindText = "text",
};

/**
 * ViewKind is one way of rendering a body.
 */
export enum ViewKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * Raw is the bytes as they arrived, split for display only.
     */
    Raw = "raw",

    /**
     * Pretty is re-indented. Only structured bodies have one.
     */
    Pretty = "pretty",
};
