/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiffIndexRouteImport } from './routes/diff.index'
import { Route as DiffPathRouteImport } from './routes/diff.$path'
import { Route as EnvIndexRouteImport } from './routes/env.index'
import { Route as EnvNameRouteImport } from './routes/env.$name'
import { Route as FIndexRouteImport } from './routes/f.index'
import { Route as FPathRouteImport } from './routes/f.$path'
import { Route as RPathRouteImport } from './routes/r.$path'
import { Route as SPathRouteImport } from './routes/s.$path'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiffIndexRoute = DiffIndexRouteImport.update({
  id: '/diff/',
  path: '/diff/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiffPathRoute = DiffPathRouteImport.update({
  id: '/diff/$path',
  path: '/diff/$path',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvIndexRoute = EnvIndexRouteImport.update({
  id: '/env/',
  path: '/env/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvNameRoute = EnvNameRouteImport.update({
  id: '/env/$name',
  path: '/env/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const FIndexRoute = FIndexRouteImport.update({
  id: '/f/',
  path: '/f/',
  getParentRoute: () => rootRouteImport,
} as any)
const FPathRoute = FPathRouteImport.update({
  id: '/f/$path',
  path: '/f/$path',
  getParentRoute: () => rootRouteImport,
} as any)
const RPathRoute = RPathRouteImport.update({
  id: '/r/$path',
  path: '/r/$path',
  getParentRoute: () => rootRouteImport,
} as any)
const SPathRoute = SPathRouteImport.update({
  id: '/s/$path',
  path: '/s/$path',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diff/$path': typeof DiffPathRoute
  '/env/$name': typeof EnvNameRoute
  '/f/$path': typeof FPathRoute
  '/r/$path': typeof RPathRoute
  '/s/$path': typeof SPathRoute
  '/diff/': typeof DiffIndexRoute
  '/env/': typeof EnvIndexRoute
  '/f/': typeof FIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diff/$path': typeof DiffPathRoute
  '/env/$name': typeof EnvNameRoute
  '/f/$path': typeof FPathRoute
  '/r/$path': typeof RPathRoute
  '/s/$path': typeof SPathRoute
  '/diff': typeof DiffIndexRoute
  '/env': typeof EnvIndexRoute
  '/f': typeof FIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diff/$path': typeof DiffPathRoute
  '/env/$name': typeof EnvNameRoute
  '/f/$path': typeof FPathRoute
  '/r/$path': typeof RPathRoute
  '/s/$path': typeof SPathRoute
  '/diff/': typeof DiffIndexRoute
  '/env/': typeof EnvIndexRoute
  '/f/': typeof FIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/diff/$path'
    | '/env/$name'
    | '/f/$path'
    | '/r/$path'
    | '/s/$path'
    | '/diff/'
    | '/env/'
    | '/f/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/diff/$path'
    | '/env/$name'
    | '/f/$path'
    | '/r/$path'
    | '/s/$path'
    | '/diff'
    | '/env'
    | '/f'
  id:
    | '__root__'
    | '/'
    | '/diff/$path'
    | '/env/$name'
    | '/f/$path'
    | '/r/$path'
    | '/s/$path'
    | '/diff/'
    | '/env/'
    | '/f/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiffPathRoute: typeof DiffPathRoute
  EnvNameRoute: typeof EnvNameRoute
  FPathRoute: typeof FPathRoute
  RPathRoute: typeof RPathRoute
  SPathRoute: typeof SPathRoute
  DiffIndexRoute: typeof DiffIndexRoute
  EnvIndexRoute: typeof EnvIndexRoute
  FIndexRoute: typeof FIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diff/': {
      id: '/diff/'
      path: '/diff'
      fullPath: '/diff/'
      preLoaderRoute: typeof DiffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diff/$path': {
      id: '/diff/$path'
      path: '/diff/$path'
      fullPath: '/diff/$path'
      preLoaderRoute: typeof DiffPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/env/': {
      id: '/env/'
      path: '/env'
      fullPath: '/env/'
      preLoaderRoute: typeof EnvIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/env/$name': {
      id: '/env/$name'
      path: '/env/$name'
      fullPath: '/env/$name'
      preLoaderRoute: typeof EnvNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/': {
      id: '/f/'
      path: '/f'
      fullPath: '/f/'
      preLoaderRoute: typeof FIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$path': {
      id: '/f/$path'
      path: '/f/$path'
      fullPath: '/f/$path'
      preLoaderRoute: typeof FPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$path': {
      id: '/r/$path'
      path: '/r/$path'
      fullPath: '/r/$path'
      preLoaderRoute: typeof RPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$path': {
      id: '/s/$path'
      path: '/s/$path'
      fullPath: '/s/$path'
      preLoaderRoute: typeof SPathRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiffPathRoute: DiffPathRoute,
  EnvNameRoute: EnvNameRoute,
  FPathRoute: FPathRoute,
  RPathRoute: RPathRoute,
  SPathRoute: SPathRoute,
  DiffIndexRoute: DiffIndexRoute,
  EnvIndexRoute: EnvIndexRoute,
  FIndexRoute: FIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
