// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * State is everything the window knows about the repository at one moment.
 */
export interface State {
    /**
     * Repository is false when the collection is not inside a git repository.
     * Every other field is then zero and nothing git-related is shown.
     */
    "repository": boolean;

    /**
     * Branch is the checked-out branch, or "" on a detached HEAD.
     */
    "branch": string;

    /**
     * Detached reports a checkout that is not on a branch; Head then names
     * the commit.
     */
    "detached": boolean;

    /**
     * Head is the short hash of the checked-out commit, "" on an empty
     * repository with no commits yet.
     */
    "head": string;

    /**
     * Ahead and Behind count commits relative to the branch's upstream. Both
     * are zero when there is no upstream to compare against.
     */
    "ahead": number;
    "behind": number;

    /**
     * HasUpstream distinguishes "0 ahead, 0 behind" from "nothing to
     * compare": a branch never pushed has no upstream, and showing it as
     * level with one would be a lie.
     */
    "hasUpstream": boolean;

    /**
     * Statuses maps a path relative to the collection root, "/"-separated, to
     * its status. Clean files are absent.
     */
    "statuses": { [_ in string]?: Status } | null;
}

/**
 * Status is a file's state in the working tree, as the one letter the status
 * bar and the tree dots show (DESIGN-NOTES §2.6).
 */
export enum Status {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * StatusClean means the file matches HEAD and the index.
     */
    StatusClean = "",

    /**
     * StatusModified is git's M: tracked and changed.
     */
    StatusModified = "M",

    /**
     * StatusUntracked is git's U: not in the index at all.
     */
    StatusUntracked = "U",

    /**
     * StatusAdded is git's A: newly staged.
     */
    StatusAdded = "A",

    /**
     * StatusDeleted is git's D. The tree cannot show a file that is gone, but
     * the status bar can still name it.
     */
    StatusDeleted = "D",
};
