// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MCP is what the person has allowed an agent to do on this machine.
 * 
 * Per-machine and never in the collection: whether *you* let an agent drive
 * your machine is not a fact about the repository, the same reasoning that
 * keeps the active environment out of it. An environment's committed
 * `$otis.agents` says what the *team* thinks about that environment; this says
 * what you have turned on.
 * 
 * The zero value is the shipped state and is the safe one: the server off and
 * all three capabilities off, with the two protections on. A new install, a
 * deleted settings file and a settings file from before this field existed all
 * read the same way, which is why the two protections are stored *inverted*.
 */
export interface MCP {
    /**
     * Enabled starts the loopback listener. Off by default: the app ships
     * with the server itself off, so turning it on is a deliberate act
     * separate from granting any capability.
     */
    "enabled": boolean;

    /**
     * Read, Run and Write are the three capabilities, all off by default.
     */
    "read": boolean;
    "run": boolean;
    "write": boolean;

    /**
     * NeverConfirmSends inverts §4 rule 4's `alwaysConfirmSends`, which is
     * **on by default** — every agent send asks until somebody turns it off,
     * which is what makes a committed `"allow"` a statement about the
     * environment rather than a grant that takes effect unasked.
     * 
     * Stored inverted because a bool's zero value is false and the default
     * here has to be *on*. Written the other way round, an older settings
     * file or a corrupt one would read as "never confirm", and a settings
     * file is a cache that is allowed to be missing (see Store.Get). A
     * default that fails towards asking is the only acceptable direction.
     */
    "neverConfirmSends": boolean;

    /**
     * DoNotPersistAuditLog inverts §9.1's `persistAuditLog`, on by default,
     * and is inverted for the same reason: a lost or truncated settings file
     * must not silently stop the recording.
     */
    "doNotPersistAuditLog": boolean;
}

/**
 * Panes is the geometry of the three-pane layout.
 */
export interface Panes {
    "sidebarWidth": number;
    "responseWidth": number;
    "sidebarCollapsed": boolean;
    "responseCollapsed": boolean;
}

/**
 * Recent is one entry in the recent-collections list.
 */
export interface Recent {
    /**
     * Name is the collection directory's base name.
     */
    "name": string;

    /**
     * Path is the absolute path of the collection directory.
     */
    "path": string;

    /**
     * LastOpened is when the collection was last opened.
     */
    "lastOpened": string;

    /**
     * Missing reports that Path no longer resolves to a directory. It is
     * computed on every read and never written to disk, so a directory that
     * comes back stops being missing on its own.
     */
    "missing": boolean;
}

/**
 * Settings is the whole persisted document. Every field is optional; the zero
 * value is a valid, empty settings file.
 */
export interface Settings {
    /**
     * Panes holds the widths of the resizable panes, in CSS pixels. Zero
     * means "never set" — the frontend then applies the design defaults from
     * docs/design/DESIGN-NOTES.md §4.1 rather than a width of nothing.
     */
    "panes": Panes;

    /**
     * Tabs is the open document tabs. Only paths are kept; tab contents and
     * dirty state are rebuilt from disk on launch.
     */
    "tabs": Tabs;

    /**
     * Recents lists recently opened collections, most recent first.
     */
    "recents": Recent[] | null;

    /**
     * LastCollection is the absolute path of the collection to reopen on
     * launch, or "" for none.
     */
    "lastCollection": string;

    /**
     * ActiveEnv is the environment selected in LastCollection, or "" for
     * none. Which environment is active is a per-machine choice, not a
     * property of the collection — one person works against staging while
     * another is on local, from the same branch — so it lives here rather
     * than in a committed file. It is cleared when the collection changes,
     * for the same reason the tabs are: an environment names a file inside
     * one collection.
     * 
     * Only the *name* is ever written here. A secret value never reaches this
     * file (docs/FORMAT.md §5).
     */
    "activeEnv": string;

    /**
     * MCP is the agent server's per-machine state (docs/MCP.md §3, §4).
     */
    "mcp": MCP;
}

/**
 * Tabs is the open document tabs, as collection-relative node IDs
 * (docs/FORMAT.md §2.1).
 */
export interface Tabs {
    "open": string[] | null;
    "active": string;
}
