// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Panes is the geometry of the three-pane layout.
 */
export interface Panes {
    "sidebarWidth": number;
    "responseWidth": number;
    "sidebarCollapsed": boolean;
    "responseCollapsed": boolean;
}

/**
 * Recent is one entry in the recent-collections list.
 */
export interface Recent {
    /**
     * Name is the collection directory's base name.
     */
    "name": string;

    /**
     * Path is the absolute path of the collection directory.
     */
    "path": string;

    /**
     * LastOpened is when the collection was last opened.
     */
    "lastOpened": string;

    /**
     * Missing reports that Path no longer resolves to a directory. It is
     * computed on every read and never written to disk, so a directory that
     * comes back stops being missing on its own.
     */
    "missing": boolean;
}

/**
 * Settings is the whole persisted document. Every field is optional; the zero
 * value is a valid, empty settings file.
 */
export interface Settings {
    /**
     * Panes holds the widths of the resizable panes, in CSS pixels. Zero
     * means "never set" — the frontend then applies the design defaults from
     * docs/design/DESIGN-NOTES.md §4.1 rather than a width of nothing.
     */
    "panes": Panes;

    /**
     * Tabs is the open document tabs. Only paths are kept; tab contents and
     * dirty state are rebuilt from disk on launch.
     */
    "tabs": Tabs;

    /**
     * Recents lists recently opened collections, most recent first.
     */
    "recents": Recent[] | null;

    /**
     * LastCollection is the absolute path of the collection to reopen on
     * launch, or "" for none.
     */
    "lastCollection": string;

    /**
     * ActiveEnv is the environment selected in LastCollection, or "" for
     * none. Which environment is active is a per-machine choice, not a
     * property of the collection — one person works against staging while
     * another is on local, from the same branch — so it lives here rather
     * than in a committed file. It is cleared when the collection changes,
     * for the same reason the tabs are: an environment names a file inside
     * one collection.
     * 
     * Only the *name* is ever written here. A secret value never reaches this
     * file (docs/FORMAT.md §5).
     */
    "activeEnv": string;
}

/**
 * Tabs is the open document tabs, as collection-relative node IDs
 * (docs/FORMAT.md §2.1).
 */
export interface Tabs {
    "open": string[] | null;
    "active": string;
}
