// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Info is the whole build identity, as one value. It crosses the Wails
 * binding so the window can show it (AppService.Build).
 */
export interface Info {
    /**
     * Version is the release version, e.g. "v0.2.0" or "dev".
     */
    "version": string;

    /**
     * Commit is the abbreviated commit, empty in an unstamped build.
     */
    "commit": string;

    /**
     * Date is the build time, RFC 3339 in UTC, empty in an unstamped build.
     */
    "date": string;

    /**
     * Go is the toolchain that built it, e.g. "go1.25.5".
     */
    "go": string;

    /**
     * Platform is the target, e.g. "darwin/arm64".
     */
    "platform": string;
}
