// Generated by internal/events/gen from internal/events/names.go.
// DO NOT EDIT. Run `go generate ./internal/events` after changing the Go side.
//
// Event names are never written as literals: Go uses the constants in
// internal/events, TypeScript uses this object.

export const OtisEvent = {
  /** Emitted once per window when its Wails runtime is ready. Payload: the version string. */
  AppReady: "app:ready",
  /** Emitted whenever the current collection changes, including on close. Payload: CollectionInfo, with an empty path when nothing is open. */
  CollectionOpened: "collection:opened",
  /** Emitted when the collection directory changed on disk. Payload: the whole Tree. */
  CollectionChanged: "collection:changed",
  /** Emitted when the repository's HEAD or index changed. Payload: the git State. */
  GitChanged: "git:changed",
  /** Emitted when Go changed the persisted settings itself. No payload; re-read the settings. */
  SettingsChanged: "settings:changed",
} as const;

export type OtisEventName = (typeof OtisEvent)[keyof typeof OtisEvent];
