// Generated by internal/events/gen from internal/events/names.go.
// DO NOT EDIT. Run `go generate ./internal/events` after changing the Go side.
//
// Event names are never written as literals: Go uses the constants in
// internal/events, TypeScript uses this object.

export const OtisEvent = {
  /** Emitted once per window when its Wails runtime is ready. Payload: the version string. */
  AppReady: "app:ready",
  /** Emitted whenever the current collection changes, including on close. Payload: CollectionInfo, with an empty path when nothing is open. */
  CollectionOpened: "collection:opened",
  /** Emitted when the collection directory changed on disk. Payload: the whole Tree. */
  CollectionChanged: "collection:changed",
  /** Emitted when the repository's HEAD or index changed. Payload: the git State. */
  GitChanged: "git:changed",
  /** Emitted when Go changed the persisted settings itself. No payload; re-read the settings. */
  SettingsChanged: "settings:changed",
  /** Emitted once a request is on the wire. Payload: SendStarted, keyed by send ID. */
  SendStarted: "send:started",
  /** Emitted when a response has been read in full. Payload: ResponseMeta; the body stays in Go. */
  SendComplete: "send:complete",
  /** Emitted when a send produced no response. Payload: SendFailure, with a masked message. */
  SendError: "send:error",
  /** Emitted when the variables a run set changed. No payload; re-read them. */
  SessionVarsChanged: "session-vars:changed",
  /** Emitted when the environments or the active one changed. Payload: Environments; never a secret value. */
  EnvironmentsChanged: "environments:changed",
  /** Emitted when a folder run begins. Payload: RunStarted, carrying every request it will send in order. */
  RunStarted: "run:started",
  /** Emitted as each request in a folder run finishes. Payload: RunResult. */
  RunResult: "run:result",
  /** Emitted when a folder run ends, however it ended. Payload: RunComplete. */
  RunComplete: "run:complete",
} as const;

export type OtisEventName = (typeof OtisEvent)[keyof typeof OtisEvent];
