// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Guard suppresses filesystem events for the paths Otis is writing itself.
 * 
 * Every write the app makes to a collection goes inside Writing:
 * 
 * 	release := guard.Writing(path)
 * 	defer release()
 * 	... write the file ...
 * 
 * The watcher then drops events for that path until the grace period after
 * release has passed. Without this, saving a request would be indistinguishable
 * from someone editing it in another editor, and the app would re-walk and
 * re-render on every keystroke it had just persisted.
 * 
 * Nothing in Phase B writes to a collection. The guard exists now because the
 * watcher has to consult it from the start; the first writer arrives in
 * Phase C.
 */
export interface Guard {
}
